# unset it if no DBBACKEND is wanted (no use of Roles)
DBBACKEND=unixgroups

SHAREDIR=${SHAREDIR:-/usr/share/blends}

# unset (NOT set it to false!) for disable dryrun 
#DRYRUN=true
# This would print debugging information
#DRYRUN="echo DRYRUN: "
#DEBUG=1

# Utility functions, backend indep
. ${SHAREDIR}/blend-utils
. ${SHAREDIR}/blend-actions

# actual action performed by choosen backend
. ${SHAREDIR}/${DBBACKEND}/blend-actions
