/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __GDL_MARSHAL_MARSHAL_H__
#define __GDL_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (./libgdlmarshal.list:1) */
#define gdl_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:ENUM (./libgdlmarshal.list:2) */
#define gdl_marshal_VOID__ENUM	g_cclosure_marshal_VOID__ENUM

/* VOID:UINT,UINT (./libgdlmarshal.list:3) */
extern
void gdl_marshal_VOID__UINT_UINT (GClosure     *closure,
                                  GValue       *return_value,
                                  guint         n_param_values,
                                  const GValue *param_values,
                                  gpointer      invocation_hint,
                                  gpointer      marshal_data);

/* VOID:BOOLEAN (./libgdlmarshal.list:4) */
#define gdl_marshal_VOID__BOOLEAN	g_cclosure_marshal_VOID__BOOLEAN

/* VOID:OBJECT,INT,INT (./libgdlmarshal.list:5) */
extern
void gdl_marshal_VOID__OBJECT_INT_INT (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:OBJECT,ENUM,BOXED (./libgdlmarshal.list:6) */
extern
void gdl_marshal_VOID__OBJECT_ENUM_BOXED (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* VOID:BOXED (./libgdlmarshal.list:7) */
#define gdl_marshal_VOID__BOXED	g_cclosure_marshal_VOID__BOXED


G_END_DECLS

#endif /* __GDL_MARSHAL_MARSHAL_H__ */
