# SPDX-License-Identifier: GPL-2.0
#
# Ubuntu Determinant project attention:
# Max Rupplin - MEARVK LLC - 2026.
#
# Project-specific build integration is maintained by MEARVK while
# the applicable upstream/kernel license remains in force.

obj-$(CONFIG_SECURITY_EPERM) += eperm.o
