Listen 9311
Listen 9312

<VirtualHost *:9311>
    WSGIScriptAlias / /usr/share/barbican/app.wsgi
    WSGIDaemonProcess barbican-api user=barbican group=barbican processes=3 threads=10
    WSGIProcessGroup barbican-api
    WSGIApplicationGroup %{GLOBAL}
    ErrorLog /var/log/barbican/barbican-api.log
    CustomLog /var/log/barbican/barbican-api.log combined
</VirtualHost>

<VirtualHost *:9312>
    WSGIScriptAlias / /usr/share/barbican/app.wsgi
    WSGIDaemonProcess barbican-api-admin user=barbican group=barbican processes=3 threads=10
    WSGIProcessGroup barbican-api-admin
    WSGIApplicationGroup %{GLOBAL}
    ErrorLog /var/log/barbican/barbican-api.log
    CustomLog /var/log/barbican/barbican-api.log combined
</VirtualHost>
