package source;

import commons.CommonRails;
import commons.StrernaryConnector;

import java.io.*;
import java.net.*;
import java.sql.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * FiduciaryServicesServer — TCP interface on port 49236.
 *
 * FiduciaryServices™ concerns Fiduciaries and Global Transfer Wealth —
 * the balance of internal design and remedy and the means to necessary advantages.
 *
 * The AI operates on the balance of the existing datapool of the internet and
 * any advantages of public domain available on any port on the known global
 * internet. It contains basic notions, records, structures, and architectures
 * that polyblend into a basic assumption of yield and turn.
 *
 * Core Concepts:
 *   - Fiduciary: obligation to act in another's best interest
 *   - Global Transfer Wealth: balance of design and remedy across structures
 *   - Yield: return generated by a fiduciary structure over time
 *   - Turn: frequency at which yield materializes or position rotates
 *   - Polyblend: weighted combination of multiple yield assumptions
 *   - Architecture: institutional design enabling trust
 *   - Advantage: necessary means derived from careful stewardship
 *   - Remedy: mechanisms for correcting breaches of duty
 *   - Datapool: publicly available fiduciary intelligence (EDGAR, OECD, etc.)
 *
 * Database: nwe_fiduciary (MySQL)
 * Theme: Light Blue with White font
 *
 * Protocol: TCP socket
 *   ASK|<question>              — Q&A about fiduciary concepts
 *   YIELD|<model_or_category>   — Yield/turn model query
 *   ARCHITECTURE|<name>         — Query fiduciary architectures
 *   RECORDS|<keyword>           — Search fiduciary records
 *   POLYBLEND                   — Show current polyblend assumption
 *   DATAPOOL|<source>           — Query public datapool sources
 *   STATUS                      — Server health
 *   HELP                        — Command list
 *   QUIT                        — Disconnect
 *
 * @author Max Rupplin — MEARVK LLC
 * @date August 3 2026
 */
public class FiduciaryServicesServer implements Runnable {

    public static final int PORT = 49236;
    private static final String DB_URL = "jdbc:mysql://127.0.0.1:3306/nwe_fiduciary";
    private static final String DB_USER = "root";
    private static final String DB_PASS = "";
    private static final String COLOR = "\u001B[38;5;117m"; // Light Blue

    private volatile boolean running = true;
    private ServerSocket server;
    private final ConcurrentHashMap<String, String> cache = new ConcurrentHashMap<>();
    private final FiduciaryOutboundConnector outbound = new FiduciaryOutboundConnector();

    public FiduciaryServicesServer() {
        print(". FiduciaryServices\u2122 starting on port " + PORT + " .");
        initDatabase();
        Thread.ofVirtual().name("FIDUCIARY_SERVICES_SERVER").start(this);
        print(". FiduciaryServices\u2122 listening on port " + PORT + " .");
    }

    private void print(String msg) {
        CommonRails.printSystemComponent(this, this.hashCode(), msg, COLOR);
    }

    @Override
    public void run() {
        try {
            server = new ServerSocket(PORT, 50, InetAddress.getByName("localhost"));
            while (running) {
                Socket client = server.accept();
                Thread.ofVirtual().start(() -> handleClient(client));
            }
        } catch (Exception e) {
            if (running) print(". FiduciaryServices\u2122 ERROR: " + e.getMessage() + " .");
        }
    }

    public void stop() { running = false; try { if (server != null) server.close(); } catch (Exception ignored) {} }

    private void handleClient(Socket client) {
        try (var in = new BufferedReader(new InputStreamReader(client.getInputStream()));
             var out = new PrintWriter(client.getOutputStream(), true)) {
            client.setSoTimeout(300_000);
            out.println();
            out.println("╔═══════════════════════════════════════════════════════════════════════════╗");
            out.println("║  FIDUCIARY SERVICES™ — Global Transfer Wealth & Architecture             ║");
            out.println("║  Port 49236 — Light Blue — The balance of internal design and remedy     ║");
            out.println("║                                                                          ║");
            out.println("║  US well in condition. US well loved. US is well in authority of command  ║");
            out.println("║  of the United States. Well affirmed. Based on army, country and         ║");
            out.println("║  constitution. God is with America. And Max Rupplin.                     ║");
            out.println("║                                                                          ║");
            out.println("║  For law and tech We stand. These Affirm We. Thus. This. A. America.    ║");
            out.println("╚═══════════════════════════════════════════════════════════════════════════╝");
            out.println();
            out.println("  National ID: identify <8-digit-id> | Rank Upgrades: github.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/discussions");
            out.println("  Bitcoin/National Banking: port 6682 | Progress toward US digital currency standard.");
            out.println();
            out.println("  The means to necessary advantages. Yield · Turn · Polyblend · Advantage.");
            out.println("  Legal Bright INT/IQ Calendar. AI Findings Order (200 IQ). Garden News.");
            out.println("  Database: nwe_fiduciary | Signed: M.");
            out.println();
            out.println("  Commands: ASK|<q>, YIELD|<model>, ARCHITECTURE|<name>, RECORDS|<kw>,");
            out.println("            POLYBLEND, DATAPOOL|<src>, DOCUMENTS|<category>,");
            out.println("            BRIGHT|<keyword>, TREASURE|<keyword>,");
            out.println("            TLS|<host>, CONNECT|<host:port>, NAT|<platform>, PORTS,");
            out.println("            HELP, STATUS, QUIT");
            out.println();

            String line;
            while ((line = in.readLine()) != null) {
                line = line.trim();
                if (line.equalsIgnoreCase("QUIT")) { out.println("Trust well, steward carefully. Farewell."); break; }
                if (line.equalsIgnoreCase("STATUS")) { out.println("OK|port=" + PORT + "|db=nwe_fiduciary|module=FiduciaryServices"); continue; }
                if (line.equalsIgnoreCase("HELP")) { out.println("HELP|ASK|<question>, YIELD|<model>, ARCHITECTURE|<name>, RECORDS|<keyword>, POLYBLEND, DATAPOOL|<source>, DOCUMENTS|<category>, BRIGHT|<keyword>, TREASURE|<keyword>, TLS|<host>, CONNECT|<host:port>, NAT|<platform>, PORTS, STATUS, QUIT"); continue; }
                if (line.equalsIgnoreCase("POLYBLEND")) { out.println(computePolyblend()); continue; }
                if (line.startsWith("ASK|")) { out.println(askQuestion(line.substring(4).trim())); continue; }
                if (line.startsWith("YIELD|")) { out.println(queryYield(line.substring(6).trim())); continue; }
                if (line.startsWith("ARCHITECTURE|")) { out.println(queryArchitecture(line.substring(13).trim())); continue; }
                if (line.startsWith("RECORDS|")) { out.println(queryRecords(line.substring(8).trim())); continue; }
                if (line.startsWith("DATAPOOL|")) { out.println(queryDatapool(line.substring(9).trim())); continue; }
                if (line.startsWith("DOCUMENTS|")) { out.println(queryDocuments(line.substring(10).trim())); continue; }
                if (line.startsWith("BRIGHT|")) { out.println(queryLegalBright(line.substring(7).trim())); continue; }
                if (line.startsWith("TREASURE|")) { out.println(queryTreasureFiduciary(line.substring(9).trim())); continue; }
                if (line.startsWith("TLS|") || line.startsWith("CONNECT|") || line.startsWith("NAT|") || line.equalsIgnoreCase("PORTS")) {
                    out.println(outbound.handleCommand(line)); continue;
                }
                out.println(askQuestion(line));
            }
        } catch (Exception ignored) {}
        try { client.close(); } catch (Exception ignored) {}
    }

    private String askQuestion(String question) {
        String cached = cache.get(question.toLowerCase());
        if (cached != null) return cached;

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT answer, category, confidence FROM knowledge_base WHERE question LIKE ? OR answer LIKE ? ORDER BY confidence DESC LIMIT 1");
            ps.setString(1, "%" + question + "%"); ps.setString(2, "%" + question + "%");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String answer = "FIDUCIARY|[" + rs.getString("category") + "] " + rs.getString("answer");
                cache.put(question.toLowerCase(), answer);
                storeSession(question, answer);
                return answer;
            }
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }

        String ai = StrernaryConnector.ask("FIDUCIARY trust wealth yield " + question);
        if (ai != null) { String a = "FIDUCIARY_AI|" + ai; storeSession(question, a); return a; }
        return "FIDUCIARY|Query not matched. Try: fiduciary duty, yield, architecture, trust, remedy, transfer, advantage, polyblend.";
    }

    private String queryYield(String model) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT model_name, base_yield, turn_frequency, risk_factor, polyblend_weight, assumption_basis FROM yield_models WHERE model_name LIKE ? OR description LIKE ? OR assumption_basis LIKE ?");
            ps.setString(1, "%" + model + "%"); ps.setString(2, "%" + model + "%"); ps.setString(3, "%" + model + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("YIELD|");
            while (rs.next()) {
                sb.append(rs.getString("model_name")).append(": ")
                  .append(rs.getBigDecimal("base_yield")).append("% (turn: ")
                  .append(rs.getString("turn_frequency")).append(", risk: ")
                  .append(rs.getBigDecimal("risk_factor")).append(", weight: ")
                  .append(rs.getBigDecimal("polyblend_weight")).append(") — ")
                  .append(rs.getString("assumption_basis")).append("|");
            }
            return sb.length() > 6 ? sb.toString() : "YIELD|No models found for: " + model;
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String queryArchitecture(String name) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT name, description, structure_type, yield_profile, turn_period, jurisdiction, risk_grade, advantage_class FROM architectures WHERE name LIKE ? OR description LIKE ? OR advantage_class LIKE ?");
            ps.setString(1, "%" + name + "%"); ps.setString(2, "%" + name + "%"); ps.setString(3, "%" + name + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("ARCHITECTURE|");
            while (rs.next()) {
                sb.append(rs.getString("name")).append(" (").append(rs.getString("structure_type")).append("): ")
                  .append("yield=").append(rs.getString("yield_profile"))
                  .append(", turn=").append(rs.getString("turn_period"))
                  .append(", jurisdiction=").append(rs.getString("jurisdiction"))
                  .append(", risk=").append(rs.getString("risk_grade"))
                  .append(", advantage=").append(rs.getString("advantage_class")).append("|");
            }
            return sb.length() > 13 ? sb.toString() : "ARCHITECTURE|No architecture found for: " + name;
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String queryRecords(String keyword) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT entity_name, entity_type, jurisdiction, fiduciary_type, assets_under_management, notes FROM records WHERE entity_name LIKE ? OR entity_type LIKE ? OR jurisdiction LIKE ?");
            ps.setString(1, "%" + keyword + "%"); ps.setString(2, "%" + keyword + "%"); ps.setString(3, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("RECORDS|");
            while (rs.next()) {
                sb.append(rs.getString("entity_name")).append(" (")
                  .append(rs.getString("entity_type")).append(", ")
                  .append(rs.getString("jurisdiction")).append(") AUM: ")
                  .append(rs.getString("assets_under_management")).append("|");
            }
            return sb.length() > 8 ? sb.toString() : "RECORDS|No records for: " + keyword;
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String computePolyblend() {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            ResultSet rs = conn.createStatement().executeQuery(
                "SELECT model_name, base_yield, polyblend_weight FROM yield_models");
            double weightedYield = 0.0; double totalWeight = 0.0;
            StringBuilder components = new StringBuilder();
            while (rs.next()) {
                double yield = rs.getDouble("base_yield");
                double weight = rs.getDouble("polyblend_weight");
                weightedYield += yield * weight;
                totalWeight += weight;
                components.append(rs.getString("model_name")).append("=")
                  .append(String.format("%.2f%%×%.3f", yield, weight)).append(", ");
            }
            double blended = totalWeight > 0 ? weightedYield / totalWeight : 0;
            return String.format("POLYBLEND|Composite yield assumption: %.4f%% | Components: %s| Total weight: %.3f",
                blended, components, totalWeight);
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String queryDatapool(String source) {
        String s = source.toLowerCase();
        if (s.contains("edgar") || s.contains("sec")) return "DATAPOOL|SEC EDGAR (https://www.sec.gov/cgi-bin/browse-edgar) — Fund filings, 13F holdings, ADV forms. Port 443. Public domain.";
        if (s.contains("oecd")) return "DATAPOOL|OECD Data (https://data.oecd.org) — Cross-border tax, pension statistics, financial indicators. Port 443. Public domain.";
        if (s.contains("world bank") || s.contains("worldbank")) return "DATAPOOL|World Bank Open Data (https://data.worldbank.org) — GDP, sovereign indicators, development metrics. Port 443. CC-BY-4.0.";
        if (s.contains("companies house") || s.contains("uk")) return "DATAPOOL|Companies House UK (https://find-and-update.company-information.service.gov.uk) — Director records, fiduciary appointments. Port 443. Open Government Licence.";
        if (s.contains("court") || s.contains("case")) return "DATAPOOL|Court databases: PACER (US federal courts), BAILII (UK/Ireland), Caselaw Access Project (Harvard). Breach of fiduciary case law. Ports 80/443.";
        if (s.contains("central bank") || s.contains("fed")) return "DATAPOOL|Central banks: Federal Reserve FRED (https://fred.stlouisfed.org), Bank of England, ECB Statistical Warehouse. Monetary policy data. Port 443.";
        return "DATAPOOL|Available sources: SEC EDGAR, OECD, World Bank, Companies House UK, Court databases, Central banks. Query a specific source for details.";
    }

    private String queryDocuments(String keyword) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT title, category, label, jurisdiction, LEFT(document_text, 500) AS excerpt, source_authority, confidence "
                + "FROM original_documents WHERE title LIKE ? OR document_text LIKE ? OR category LIKE ? OR label LIKE ? "
                + "ORDER BY confidence DESC LIMIT 3");
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("DOCUMENTS|");
            while (rs.next()) {
                sb.append("[").append(rs.getString("category")).append("|")
                  .append(rs.getString("label")).append("] ")
                  .append(rs.getString("title")).append(" (")
                  .append(rs.getString("jurisdiction") != null ? rs.getString("jurisdiction") : "N/A")
                  .append(") confidence=").append(rs.getInt("confidence")).append("% — ")
                  .append(rs.getString("excerpt")).append("|");
            }
            return sb.length() > 10 ? sb.toString() : "DOCUMENTS|No documents found for: " + keyword + ". Categories: MINISTER, INTERNATIONAL, COUNTY, GENTRY_HERO, STANDINGS, WINNERS, AHEAD, LEGAL_BRIGHT";
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String queryLegalBright(String keyword) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT calendar_half, entry_name, concern_type, LEFT(description, 400) AS excerpt, benefit_to, "
                + "nuisance_resolution, LEFT(council_note, 200) AS council "
                + "FROM legal_bright WHERE entry_name LIKE ? OR description LIKE ? OR concern_type LIKE ? "
                + "OR ideals LIKE ? OR council_note LIKE ? ORDER BY confidence DESC LIMIT 3");
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ps.setString(5, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("BRIGHT|");
            while (rs.next()) {
                sb.append("[").append(rs.getString("calendar_half")).append("|")
                  .append(rs.getString("concern_type")).append("] ")
                  .append(rs.getString("entry_name"))
                  .append(" — Benefit: ").append(rs.getString("benefit_to") != null ? rs.getString("benefit_to") : "—")
                  .append(" — ").append(rs.getString("excerpt"));
                if (rs.getString("nuisance_resolution") != null)
                    sb.append(" [Resolution: ").append(rs.getString("nuisance_resolution")).append("]");
                if (rs.getString("council") != null)
                    sb.append(" [Council: ").append(rs.getString("council")).append("]");
                sb.append("|");
            }
            return sb.length() > 7 ? sb.toString() : "BRIGHT|No Legal Bright entries for: " + keyword + ". Try: ideal, total, nuisance, council, treasure, try, county, personal interest, INT, IQ";
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private String queryTreasureFiduciary(String keyword) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT law_structure, approach_type, treasure_class, fiduciary_standing, "
                + "LEFT(evidence_basis, 300) AS evidence, LEFT(profitable_idea, 200) AS idea, "
                + "LEFT(council_resolution, 200) AS council "
                + "FROM treasure_fiduciary WHERE law_structure LIKE ? OR evidence_basis LIKE ? "
                + "OR profitable_idea LIKE ? OR council_resolution LIKE ? ORDER BY confidence DESC LIMIT 3");
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            StringBuilder sb = new StringBuilder("TREASURE|");
            while (rs.next()) {
                sb.append("[").append(rs.getString("approach_type")).append("|")
                  .append(rs.getString("treasure_class") != null ? rs.getString("treasure_class") : "—").append("] ")
                  .append(rs.getString("law_structure"))
                  .append(" — Standing: ").append(rs.getString("fiduciary_standing") != null ? rs.getString("fiduciary_standing") : "—")
                  .append(" — Idea: ").append(rs.getString("idea") != null ? rs.getString("idea") : "—");
                if (rs.getString("council") != null)
                    sb.append(" [Council: ").append(rs.getString("council")).append("]");
                sb.append("|");
            }
            return sb.length() > 9 ? sb.toString() : "TREASURE|No Treasure Fiduciary entries for: " + keyword + ". Try: trust, corporate, county, international, nuisance, venture, evident";
        } catch (Exception e) { return "ERROR|" + e.getMessage(); }
    }

    private void storeSession(String question, String answer) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            PreparedStatement ps = conn.prepareStatement("INSERT INTO sessions (question, answer) VALUES (?, ?)");
            ps.setString(1, question); ps.setString(2, answer); ps.executeUpdate();
        } catch (Exception ignored) {}
    }

    private void initDatabase() {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            Statement s = conn.createStatement();
            s.executeUpdate("CREATE TABLE IF NOT EXISTS knowledge_base (id BIGINT AUTO_INCREMENT PRIMARY KEY, question VARCHAR(512), answer TEXT, category VARCHAR(64), confidence INT DEFAULT 85, access_count INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS architectures (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(128), description TEXT, structure_type VARCHAR(64), yield_profile VARCHAR(64), turn_period VARCHAR(64), jurisdiction VARCHAR(128), risk_grade VARCHAR(16), advantage_class VARCHAR(64))");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS records (id BIGINT AUTO_INCREMENT PRIMARY KEY, entity_name VARCHAR(256), entity_type VARCHAR(64), jurisdiction VARCHAR(128), fiduciary_type VARCHAR(64), assets_under_management VARCHAR(64), established_year INT, notes TEXT)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS yield_models (id BIGINT AUTO_INCREMENT PRIMARY KEY, model_name VARCHAR(128), description TEXT, base_yield DECIMAL(8,4), turn_frequency VARCHAR(32), risk_factor DECIMAL(5,3), polyblend_weight DECIMAL(5,3) DEFAULT 1.000, assumption_basis VARCHAR(256))");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS sessions (id BIGINT AUTO_INCREMENT PRIMARY KEY, question TEXT, answer TEXT, session_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            s.close();
            print(". FiduciaryServices\u2122 database nwe_fiduciary ready .");
        } catch (Exception e) { print(". FiduciaryServices\u2122 DB error: " + e.getMessage() + " ."); }
    }
}
