/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Auto-generated inline header for EPMP protocol specification JSON
 * This is included directly in epmp.c as a string literal.
 *
 * To regenerate: convert port_mux_spec.json to C string literal
 */
"{"
"\"protocol\":\"Extended Port Multiplexing Protocol (EPMP)\","
"\"version\":\"1.0.0\","
"\"service_port\":64444,"
"\"description\":\"Port 64444 services the multiplexing of port addresses for ports beyond the standard 2^16 (65536) range, extending addressable port space to 30 quintillion (30,000,000,000,000,000,000).\","
"\"extended_port_range\":{"
  "\"min\":0,"
  "\"max\":\"30000000000000000000\","
  "\"legacy_range\":\"0-65535\","
  "\"extended_range\":\"65536-30000000000000000000\","
  "\"addressing_bits\":65,"
  "\"note\":\"Ports 0-65535 remain directly addressable via standard TCP/UDP headers. Ports above 65535 require multiplexing through port 64444.\""
"},"
"\"discovery\":{"
  "\"trigger\":{"
    "\"description\":\"Send ASCII '1' or '1s' to port 64444 TCP to receive this spec.\","
    "\"request_single\":\"0x31\","
    "\"request_stream\":\"0x31 0x73\","
    "\"transport\":\"TCP\""
  "},"
  "\"response_format\":\"application/json\""
"},"
"\"handshake\":{"
  "\"phase_1_key_exchange\":{"
    "\"algorithm\":\"Diffie-Hellman\","
    "\"minimum_bits\":2048,"
    "\"recommended_bits\":4096,"
    "\"group\":\"RFC 3526 Group 14 (2048-bit) or Group 16 (4096-bit)\","
    "\"steps\":["
      "{\"step\":1,\"direction\":\"client->server\",\"action\":\"Send DH public value g^a mod p\",\"encoding\":\"base64\"},"
      "{\"step\":2,\"direction\":\"server->client\",\"action\":\"Send DH public value g^b mod p\",\"encoding\":\"base64\"},"
      "{\"step\":3,\"direction\":\"both\",\"action\":\"Compute shared secret g^ab mod p, derive AES-256 key via HKDF-SHA256\"}"
    "]"
  "},"
  "\"phase_2_rsa_exchange\":{"
    "\"algorithm\":\"RSA\","
    "\"minimum_bits\":2048,"
    "\"recommended_bits\":4096,"
    "\"padding\":\"OAEP-SHA256\","
    "\"signature\":\"PSS-SHA256\","
    "\"steps\":["
      "{\"step\":4,\"direction\":\"client->server\",\"action\":\"Send RSA pubkey encrypted with DH-derived AES-256\",\"format\":\"DER/PKCS#8\"},"
      "{\"step\":5,\"direction\":\"server->client\",\"action\":\"Send RSA pubkey encrypted with DH-derived AES-256\",\"format\":\"DER/PKCS#8\"},"
      "{\"step\":6,\"direction\":\"server->client\",\"action\":\"Send session confirmation signed with server RSA private key\"}"
    "]"
  "},"
  "\"phase_3_data_mode\":{"
    "\"description\":\"Client declares payload encryption mode for the session.\","
    "\"steps\":["
      "{\"step\":7,\"direction\":\"client->server\",\"action\":\"Send data_mode\",\"values\":{\"0\":\"raw - plaintext payloads\",\"1\":\"encrypted - RSA-encrypted per message\",\"2\":\"hybrid - AES-256-GCM with RSA-wrapped session key\"}},"
      "{\"step\":8,\"direction\":\"server->client\",\"action\":\"Acknowledge mode, session established\"}"
    "]"
  "}"
"},"
"\"frame_header\":{"
  "\"total_bytes\":42,"
  "\"fields\":["
    "{\"name\":\"magic\",\"type\":\"uint32\",\"value\":\"0x45504D50\"},"
    "{\"name\":\"version\",\"type\":\"uint8\",\"value\":1},"
    "{\"name\":\"target_port\",\"type\":\"uint64\",\"range\":\"0-30000000000000000000\"},"
    "{\"name\":\"source_port\",\"type\":\"uint64\",\"range\":\"0-30000000000000000000\"},"
    "{\"name\":\"payload_length\",\"type\":\"uint64\"},"
    "{\"name\":\"flags\",\"type\":\"uint16\",\"bits\":{\"0\":\"encrypted\",\"1\":\"fragmented\",\"2\":\"final_fragment\",\"3\":\"priority\"}},"
    "{\"name\":\"sequence\",\"type\":\"uint32\"},"
    "{\"name\":\"checksum\",\"type\":\"uint32\",\"algorithm\":\"CRC-32C\"}"
  "]"
"},"
"\"error_codes\":{"
  "\"0x00\":\"SUCCESS\","
  "\"0x01\":\"INVALID_PORT\","
  "\"0x02\":\"PORT_UNREACHABLE\","
  "\"0x03\":\"HANDSHAKE_FAILED\","
  "\"0x04\":\"DECRYPTION_ERROR\","
  "\"0x05\":\"SEQUENCE_ERROR\","
  "\"0x06\":\"CHECKSUM_MISMATCH\","
  "\"0x07\":\"MODE_MISMATCH\","
  "\"0x08\":\"SESSION_EXPIRED\","
  "\"0x09\":\"RATE_LIMITED\""
"},"
"\"security\":[\"DH >= 2048 bits\",\"RSA >= 2048 bits\",\"Session timeout: 3600s\",\"Rate limit: 5 failed handshakes/min/IP\",\"Protect port 64444 with firewall (UFW/iptables/nftables)\"],"
"\"firewall\":{\"ufw\":\"ufw allow 64444/tcp\",\"iptables\":\"iptables -A INPUT -p tcp --dport 64444 -j ACCEPT\",\"nftables\":\"nft add rule inet filter input tcp dport 64444 accept\"}"
"}"
