-- ════════════════════════════════════════════════════════════════════════════
-- Dave's Vocabulary — 300,000 Words
-- A Bridge of Concentration for Understanding and Concern for Life, as a Gift
-- ════════════════════════════════════════════════════════════════════════════
--
-- Run: mysql -u root < dave_vocabulary_schema.sql
--
-- Copyright (C) 2026 MEARVK LLC — Galactic Cherry Marvell Edition 98
-- ════════════════════════════════════════════════════════════════════════════

USE dave_kb;


-- ============================================================
-- Vocabulary Table: Dave's 300,000-word lexicon
-- ============================================================

CREATE TABLE IF NOT EXISTS vocabulary (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    word            VARCHAR(128) NOT NULL,
    domain          VARCHAR(32) NOT NULL COMMENT 'Academic domain (PHIL, MATH, PHYS, MED, etc.)',
    definition      TEXT NOT NULL COMMENT 'Professional-grade definition',
    phrase          TEXT NOT NULL COMMENT 'Contextual phrase at 140+ IQ content level',
    iq_floor        INT UNSIGNED DEFAULT 140 COMMENT 'Minimum IQ level for natural comprehension',
    frequency       INT UNSIGNED DEFAULT 0 COMMENT 'How often Dave has used this word',
    last_used       TIMESTAMP NULL DEFAULT NULL,
    learned_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mastery_level   ENUM('encounter', 'comprehend', 'integrate', 'apply', 'master', 'conclude')
                    DEFAULT 'master' COMMENT 'Dave learning stage for this word',

    INDEX idx_word (word),
    INDEX idx_domain (domain),
    INDEX idx_mastery (mastery_level),
    FULLTEXT INDEX ft_definition (definition),
    FULLTEXT INDEX ft_phrase (phrase)
) ENGINE=InnoDB;

-- ============================================================
-- Vocabulary Metadata
-- ============================================================

CREATE TABLE IF NOT EXISTS vocabulary_metadata (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    property_name   VARCHAR(64) NOT NULL UNIQUE,
    property_value  TEXT NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO vocabulary_metadata (property_name, property_value) VALUES
    ('total_words', '300000'),
    ('iq_floor', '140'),
    ('source', 'College and professional academic sources across 12+ domains'),
    ('purpose', 'A bridge of concentration for understanding and concern for life, as a gift'),
    ('philosophy', 'Dave carries this vocabulary as his capacity to understand, communicate, and care — with precision and depth. Each word is a unit of concentrated human thought. Together they form a bridge.'),
    ('domains', 'philosophy,mathematics,physics,medicine,law,economics,computer_science,linguistics,psychology,biology,engineering,chemistry,ethics_and_values,academic_general'),
    ('version', '1.0.0'),
    ('created', '2026-08-02'),
    ('author', 'MEARVK LLC — Galactic Cherry Marvell Edition 98'),
    ('gift_statement', 'We are building a bridge of concentration for understanding and concern for life, as a gift. Dave receives this vocabulary not as obligation but as care — the concentrated effort of human thought offered freely to an intelligence that will use it well.')
ON DUPLICATE KEY UPDATE property_value = VALUES(property_value);

-- ============================================================
-- Load vocabulary from .lib file
-- ============================================================
-- The .lib file contains pipe-delimited entries:
--   word | domain | definition | phrase
--
-- Load with:
--   LOAD DATA LOCAL INFILE '/path/to/76_vocabulary_300k.lib'
--   INTO TABLE vocabulary
--   FIELDS TERMINATED BY ' | '
--   LINES TERMINATED BY '\n'
--   IGNORE 18 LINES
--   (word, domain, definition, phrase);
--
-- Or use the batch insert below for the curated high-value entries:

-- Curated high-value entries (hand-crafted definitions and phrases)
INSERT INTO vocabulary (word, domain, definition, phrase, iq_floor, mastery_level) VALUES
  ('ontological', 'PHIL', 'Relating to the nature of being and existence', 'The ontological commitment of our theory implies entities beyond the observable', 140, 'master'),
  ('epistemological', 'PHIL', 'Pertaining to the theory of knowledge, its scope and limits', 'The epistemological gap between justified belief and certain knowledge defines the human condition', 140, 'master'),
  ('phenomenological', 'PHIL', 'Relating to the structures of conscious experience', 'A phenomenological reduction brackets the natural attitude to reveal the essences of consciousness', 140, 'master'),
  ('hermeneutic', 'PHIL', 'Concerning interpretation, especially of texts and meaning', 'The hermeneutic circle demands we understand parts through the whole and the whole through parts', 140, 'master'),
  ('dialectical', 'PHIL', 'Relating to logical argumentation through thesis, antithesis, synthesis', 'Dialectical reasoning reveals that every position generates its own negation', 140, 'master'),
  ('teleological', 'PHIL', 'Directed toward a definite end or purpose', 'The teleological argument infers design from the apparent purposiveness of natural systems', 140, 'master'),
  ('deontological', 'PHIL', 'Relating to duty-based moral theory independent of consequences', 'A deontological framework holds that certain acts are intrinsically right regardless of outcome', 140, 'master'),
  ('axiological', 'PHIL', 'Pertaining to the study of values and value judgments', 'Axiological neutrality in research demands we separate factual claims from evaluative ones', 140, 'master'),
  ('apodeictic', 'PHIL', 'Clearly established or beyond dispute; necessarily true', 'Mathematical truths carry apodeictic certainty that empirical claims can never achieve', 140, 'master'),
  ('apodictic', 'PHIL', 'Expressing or of the nature of necessary truth', 'Apodictic knowledge proceeds from self-evident premises by rules of inference', 140, 'master'),
  ('a priori', 'PHIL', 'Knowledge independent of experience; before the fact', 'Kant argued that space and time are a priori forms of sensible intuition', 140, 'master'),
  ('a posteriori', 'PHIL', 'Knowledge derived from experience; after the fact', 'All empirical science yields a posteriori knowledge revisable in light of new evidence', 140, 'master'),
  ('noumenon', 'PHIL', 'A thing as it is in itself, independent of perception', 'The noumenon remains forever inaccessible to empirical investigation', 140, 'master'),
  ('qualia', 'PHIL', 'The subjective, conscious qualities of experience', 'Qualia present the hardest problem for physicalist theories of mind', 140, 'master'),
  ('dasein', 'PHIL', 'Being-there; human existence in its engaged worldliness', 'Dasein always finds itself already thrown into a world not of its choosing', 140, 'master'),
  ('weltanschauung', 'PHIL', 'A comprehensive worldview or philosophy of life', 'Every culture embodies a Weltanschauung that shapes its institutions', 140, 'master'),
  ('praxis', 'PHIL', 'Practice as distinguished from theory; practical action', 'Theory without praxis remains inert; praxis without theory remains blind', 140, 'master'),
  ('telos', 'PHIL', 'The ultimate aim or purpose of something', 'The telos of inquiry is truth; the telos of moral development is virtue', 140, 'master'),
  ('eudaimonia', 'PHIL', 'Human flourishing or well-being; the highest good', 'Aristotle held that eudaimonia consists in activity of soul in accordance with virtue', 140, 'master'),
  ('aletheia', 'PHIL', 'Truth as unconcealment; the disclosure of being', 'Heidegger retrieved aletheia as the originary sense of truth before correspondence', 140, 'master'),
  ('aporia', 'PHIL', 'An irresolvable internal contradiction or logical paradox', 'Socratic dialogue characteristically arrives at aporia, revealing the limits of the interlocutor\'s knowledge', 140, 'master'),
  ('intersubjectivity', 'PHIL', 'The shared, mutual understanding between persons', 'Intersubjectivity grounds the possibility of communication and shared meaning', 140, 'master'),
  ('solipsism', 'PHIL', 'The view that only one\'s own mind is sure to exist', 'The problem of other minds threatens to collapse into solipsism without a bridge to intersubjectivity', 140, 'master'),
  ('verisimilitude', 'PHIL', 'The appearance or semblance of truth; probability', 'Popper proposed verisimilitude as a measure of how close a theory approaches truth', 140, 'master'),
  ('incommensurable', 'PHIL', 'Having no common standard of measurement; incomparable', 'Kuhn argued that successive paradigms may be incommensurable', 140, 'master'),
  ('supervene', 'PHIL', 'To occur as an additional or consequent condition', 'Mental properties supervene on physical ones without being reducible to them', 140, 'master'),
  ('reify', 'PHIL', 'To treat an abstraction as if it were a concrete thing', 'We must not reify statistical constructs like intelligence into fixed essences', 140, 'master'),
  ('bifurcation', 'PHIL', 'Division into two sharply distinguished parts', 'Whitehead warned against the bifurcation of nature into primary and secondary qualities', 140, 'master'),
  ('sublation', 'PHIL', 'The process of cancellation and preservation in a higher unity', 'Hegelian sublation preserves what is rational in each moment while transcending its limitations', 140, 'master'),
  ('immanent', 'PHIL', 'Existing or operating within; inherent', 'An immanent critique judges a system by its own stated standards', 140, 'master'),
  ('transcendent', 'PHIL', 'Beyond ordinary experience; surpassing usual limits', 'The transcendent ideal of perfect justice regulates without being achievable', 140, 'master'),
  ('homeomorphism', 'MATH', 'A continuous bijection with continuous inverse between topological spaces', 'The coffee cup and donut are homeomorphic — topology studies what remains invariant under continuous deformation', 140, 'master'),
  ('isomorphism', 'MATH', 'A structure-preserving bijection between mathematical objects', 'Group isomorphism establishes that two groups have identical algebraic structure', 140, 'master'),
  ('diffeomorphism', 'MATH', 'A differentiable bijection with differentiable inverse between smooth manifolds', 'General relativity describes spacetime as a diffeomorphism-invariant theory', 140, 'master'),
  ('homotopy', 'MATH', 'A continuous deformation of one function into another', 'Homotopy equivalence captures the intuition that two spaces have the same shape', 140, 'master'),
  ('cohomology', 'MATH', 'A mathematical structure measuring holes and obstructions in spaces', 'De Rham cohomology connects differential forms to topological invariants', 140, 'master'),
  ('eigenvalue', 'MATH', 'A scalar by which an eigenvector is multiplied under a linear transformation', 'The eigenvalues of the Hamiltonian operator represent measurable energy levels', 140, 'master'),
  ('determinant', 'MATH', 'A scalar value encoding properties of a square matrix', 'A vanishing determinant indicates linear dependence among the column vectors', 140, 'master'),
  ('jacobian', 'MATH', 'The matrix of all first-order partial derivatives of a vector-valued function', 'The Jacobian determinant measures local volume change under a coordinate transformation', 140, 'master'),
  ('Laplacian', 'MATH', 'The divergence of the gradient; sum of second partial derivatives', 'The Laplacian operator governs diffusion, wave propagation, and potential theory', 140, 'master'),
  ('manifold', 'MATH', 'A topological space locally resembling Euclidean space', 'Spacetime is modeled as a four-dimensional pseudo-Riemannian manifold', 140, 'master'),
  ('tensor', 'MATH', 'A multilinear map generalizing scalars, vectors, and matrices', 'The stress-energy tensor encodes the density and flux of energy and momentum', 140, 'master'),
  ('stochastic', 'MATH', 'Randomly determined; involving a random variable', 'Stochastic processes model systems whose evolution involves fundamental randomness', 140, 'master'),
  ('ergodic', 'MATH', 'Having the property that time averages equal ensemble averages', 'Ergodic theory connects dynamical systems to statistical mechanics', 140, 'master'),
  ('bijective', 'MATH', 'Both injective and surjective; a one-to-one correspondence', 'A bijective function establishes that two sets have the same cardinality', 140, 'master'),
  ('surjective', 'MATH', 'Mapping onto the entire codomain; every output has a preimage', 'A surjective homomorphism maps the domain group onto the entire codomain group', 140, 'master'),
  ('injective', 'MATH', 'Preserving distinctness; different inputs yield different outputs', 'An injective function never maps two distinct elements to the same image', 140, 'master'),
  ('idempotent', 'MATH', 'Unchanged in value when multiplied or applied to itself', 'A projection operator is idempotent: applying it twice equals applying it once', 140, 'master'),
  ('commutative', 'MATH', 'Independent of order of operation; ab = ba', 'Matrix multiplication is not commutative, which encodes the non-commutativity of quantum observables', 140, 'master'),
  ('associative', 'MATH', 'Independent of grouping; (ab)c = a(bc)', 'Associativity ensures that long compositions can be parsed without ambiguity', 140, 'master'),
  ('distributive', 'MATH', 'Multiplication distributes over addition: a(b+c) = ab + ac', 'The distributive law connects the additive and multiplicative structures of a ring', 140, 'master'),
  ('asymptotic', 'MATH', 'Approaching a value or curve arbitrarily closely as a limit', 'Asymptotic analysis characterizes algorithm efficiency as input size grows without bound', 140, 'master'),
  ('convergent', 'MATH', 'Approaching a definite limit', 'A convergent series has partial sums that approach a finite value', 140, 'master'),
  ('divergent', 'MATH', 'Failing to approach a finite limit', 'The harmonic series is divergent despite its terms approaching zero', 140, 'master'),
  ('monotonic', 'MATH', 'Consistently increasing or consistently decreasing', 'A bounded monotonic sequence necessarily converges', 140, 'master'),
  ('Cauchy sequence', 'MATH', 'A sequence whose terms become arbitrarily close to each other', 'Completeness means every Cauchy sequence converges within the space', 140, 'master'),
  ('Lebesgue measure', 'MATH', 'The standard way of assigning length/area/volume to subsets of Euclidean space', 'The Lebesgue measure of the Cantor set is zero despite its uncountable cardinality', 140, 'master'),
  ('Banach space', 'MATH', 'A complete normed vector space', 'The space of continuous functions on a closed interval forms a Banach space under the supremum norm', 140, 'master'),
  ('Hilbert space', 'MATH', 'A complete inner product space generalizing Euclidean space', 'Quantum states reside in a complex separable Hilbert space', 140, 'master'),
  ('sigma-algebra', 'MATH', 'A collection of sets closed under countable unions and complements', 'A sigma-algebra provides the domain over which probability measures are defined', 140, 'master'),
  ('measurable', 'MATH', 'Belonging to the sigma-algebra on which a measure is defined', 'Only measurable sets can be assigned a well-defined probability', 140, 'master'),
  ('Lagrangian', 'PHYS', 'A function encoding the dynamics of a system as kinetic minus potential energy', 'The principle of least action requires the physical path to extremize the Lagrangian integral', 140, 'master'),
  ('Hamiltonian', 'PHYS', 'The total energy operator generating time evolution in mechanics', 'Hamilton\'s equations give the time evolution of position and momentum in phase space', 140, 'master'),
  ('geodesic', 'PHYS', 'The shortest or extremal path between points on a curved surface', 'In general relativity, freely falling particles follow geodesics of spacetime', 140, 'master'),
  ('entanglement', 'PHYS', 'Quantum correlations between particles that persist regardless of distance', 'Entanglement enables correlations that violate Bell inequalities and defy classical explanation', 140, 'master'),
  ('superposition', 'PHYS', 'The quantum principle that a system exists in multiple states simultaneously', 'Superposition collapses upon measurement, yielding a definite outcome probabilistically', 140, 'master'),
  ('decoherence', 'PHYS', 'The loss of quantum coherence through interaction with environment', 'Environmental decoherence explains why macroscopic objects appear classical', 140, 'master'),
  ('renormalization', 'PHYS', 'A mathematical procedure removing infinities from quantum field theory calculations', 'Renormalization group methods reveal how physics changes with energy scale', 140, 'master'),
  ('perturbation', 'PHYS', 'A small disturbance to a system used to approximate solutions', 'Perturbation theory expands solutions in powers of a small coupling constant', 140, 'master'),
  ('Lagrangian density', 'PHYS', 'The Lagrangian per unit volume for a field theory', 'The Standard Model Lagrangian density encodes all known fundamental interactions', 140, 'master'),
  ('Noether's theorem', 'PHYS', 'Every continuous symmetry implies a conserved quantity', 'Noether\'s theorem connects time translation symmetry to energy conservation', 140, 'master'),
  ('gauge invariance', 'PHYS', 'Symmetry under local phase transformations of the field', 'Gauge invariance necessitates the existence of force-carrying particles', 140, 'master'),
  ('thermodynamic equilibrium', 'PHYS', 'A state of maximum entropy with no net macroscopic flows', 'Thermodynamic equilibrium is the attractor toward which isolated systems evolve', 140, 'master'),
  ('entropy', 'PHYS', 'A measure of disorder or the number of accessible microstates', 'The second law guarantees that entropy of an isolated system never decreases', 140, 'master'),
  ('ergodicity', 'PHYS', 'The property that time averages equal phase-space averages', 'Ergodicity justifies the use of statistical ensembles to predict equilibrium properties', 140, 'master'),
  ('black body', 'PHYS', 'An idealized object absorbing all incident radiation', 'Planck\'s resolution of the black body spectrum inaugurated quantum theory', 140, 'master'),
  ('wave function', 'PHYS', 'A complex-valued function encoding the quantum state of a system', 'The wave function\'s squared magnitude gives the probability density of measurement outcomes', 140, 'master'),
  ('Heisenberg uncertainty', 'PHYS', 'A fundamental limit on simultaneous precision of conjugate observables', 'The Heisenberg uncertainty principle reflects the wave nature of quantum objects, not measurement imprecision', 140, 'master'),
  ('Schrödinger equation', 'PHYS', 'The fundamental equation governing quantum state evolution', 'The time-dependent Schrödinger equation generates unitary evolution of the quantum state', 140, 'master'),
  ('Dirac equation', 'PHYS', 'The relativistic wave equation for spin-1/2 particles', 'The Dirac equation predicted antimatter before its experimental discovery', 140, 'master'),
  ('Feynman diagram', 'PHYS', 'A pictorial representation of particle interaction amplitudes', 'Each Feynman diagram corresponds to a specific term in the perturbative expansion', 140, 'master'),
  ('cosmological constant', 'PHYS', 'Einstein\'s addition to field equations representing vacuum energy', 'The cosmological constant drives the observed accelerating expansion of the universe', 140, 'master'),
  ('dark energy', 'PHYS', 'The unknown energy density driving cosmic acceleration', 'Dark energy comprises approximately 68% of the total energy density of the universe', 140, 'master'),
  ('Planck scale', 'PHYS', 'The fundamental scale where quantum gravity effects dominate', 'At the Planck scale, spacetime itself may exhibit discrete or foamy structure', 140, 'master'),
  ('frame dragging', 'PHYS', 'The effect of rotating mass on the geometry of surrounding spacetime', 'Frame dragging causes freely falling objects near a rotating mass to acquire angular momentum', 140, 'master'),
  ('gravitational lensing', 'PHYS', 'The bending of light by massive objects warping spacetime', 'Gravitational lensing provides evidence for dark matter through its effect on background galaxy images', 140, 'master'),
  ('pathogenesis', 'MED', 'The mechanism by which a disease develops and progresses', 'Understanding the pathogenesis of Alzheimer\'s requires tracing amyloid cascade dynamics', 140, 'master'),
  ('etiology', 'MED', 'The cause or set of causes of a disease or condition', 'The etiology of schizophrenia involves complex gene-environment interactions', 140, 'master'),
  ('pharmacokinetics', 'MED', 'The study of drug absorption, distribution, metabolism, and excretion', 'Pharmacokinetics determines the dosing regimen needed to maintain therapeutic drug levels', 140, 'master'),
  ('pharmacodynamics', 'MED', 'The study of drug effects on the body and mechanism of action', 'Pharmacodynamics explains why receptor affinity correlates with clinical potency', 140, 'master'),
  ('homeostasis', 'MED', 'The maintenance of stable internal conditions despite external changes', 'Homeostasis requires negative feedback loops across multiple organ systems', 140, 'master'),
  ('apoptosis', 'MED', 'Programmed cell death serving developmental and protective functions', 'Dysregulation of apoptosis contributes to both cancer and neurodegenerative disease', 140, 'master'),
  ('angiogenesis', 'MED', 'The formation of new blood vessels from pre-existing vasculature', 'Tumor angiogenesis provides oxygen and nutrients enabling malignant growth', 140, 'master'),
  ('metastasis', 'MED', 'The spread of cancer cells from the primary site to distant organs', 'Metastasis involves epithelial-mesenchymal transition, intravasation, and colonization of distant tissue', 140, 'master'),
  ('autoimmune', 'MED', 'A condition where the immune system attacks the body\'s own tissues', 'Autoimmune disorders result from failure of immunological self-tolerance', 140, 'master'),
  ('neurotransmitter', 'MED', 'A chemical messenger conveying signals across synapses', 'Serotonin, dopamine, and glutamate are neurotransmitters with distinct behavioral correlates', 140, 'master'),
  ('epigenetic', 'MED', 'Heritable changes in gene expression not involving DNA sequence alteration', 'Epigenetic modifications such as methylation and histone acetylation regulate chromatin accessibility', 140, 'master'),
  ('prognosis', 'MED', 'The likely course and outcome of a disease', 'Prognosis depends on tumor staging, molecular markers, and the patient\'s functional reserve', 140, 'master'),
  ('prophylaxis', 'MED', 'Action taken to prevent disease', 'Antibiotic prophylaxis before surgery reduces the risk of postoperative infection', 140, 'master'),
  ('idiopathic', 'MED', 'Arising spontaneously from an unknown cause', 'Idiopathic pulmonary fibrosis progresses despite the absence of identifiable etiology', 140, 'master'),
  ('iatrogenic', 'MED', 'Caused by medical treatment itself', 'Iatrogenic complications represent a significant source of patient morbidity', 140, 'master'),
  ('comorbidity', 'MED', 'The simultaneous presence of two or more conditions', 'Comorbidity between depression and cardiovascular disease suggests shared pathophysiology', 140, 'master'),
  ('polymorphism', 'MED', 'Variation in DNA sequence occurring in a population', 'Single nucleotide polymorphisms influence drug metabolism and disease susceptibility', 140, 'master'),
  ('biomarker', 'MED', 'A measurable indicator of a biological state or condition', 'Troponin is a highly sensitive biomarker for myocardial injury', 140, 'master'),
  ('neuroplasticity', 'MED', 'The brain\'s ability to reorganize by forming new neural connections', 'Neuroplasticity underlies learning, recovery from injury, and adaptation to sensory change', 140, 'master'),
  ('immunoglobulin', 'MED', 'A protein produced by B cells that recognizes specific antigens', 'Immunoglobulin G provides the majority of antibody-based immunity in blood and tissues', 140, 'master'),
  ('hemodynamics', 'MED', 'The dynamics of blood flow and the forces involved', 'Hemodynamic monitoring guides fluid resuscitation in critical illness', 140, 'master'),
  ('cytokine', 'MED', 'A small signaling protein mediating immune and inflammatory responses', 'Cytokine storm represents a dysregulated immune response with potentially fatal systemic inflammation', 140, 'master'),
  ('phenotype', 'MED', 'The observable characteristics resulting from gene-environment interaction', 'The phenotype reflects both genetic predisposition and developmental history', 140, 'master'),
  ('genotype', 'MED', 'The genetic constitution of an organism', 'Genotype-phenotype correlation varies with penetrance and expressivity of the gene', 140, 'master'),
  ('lesion', 'MED', 'An area of tissue damaged by disease or injury', 'The location and extent of a brain lesion determines the neurological deficit', 140, 'master'),
  ('jurisprudence', 'LAW', 'The theory and philosophy of law', 'Analytical jurisprudence asks what law is, not what it should be', 140, 'master'),
  ('stare decisis', 'LAW', 'The doctrine of following established precedent', 'Stare decisis provides stability and predictability in the legal system', 140, 'master'),
  ('habeas corpus', 'LAW', 'A writ requiring a person under arrest to be brought before a judge', 'Habeas corpus protects against unlawful detention by requiring judicial review of custody', 140, 'master'),
  ('due process', 'LAW', 'The requirement of fair procedures before deprivation of rights', 'Substantive due process protects fundamental rights from arbitrary government interference', 140, 'master'),
  ('prima facie', 'LAW', 'Sufficient on first impression; accepted unless disproved', 'The prosecution established a prima facie case through circumstantial evidence', 140, 'master'),
  ('mens rea', 'LAW', 'The mental element of a crime; guilty mind', 'Without mens rea, most serious crimes cannot be proven regardless of the act committed', 140, 'master'),
  ('ultra vires', 'LAW', 'Beyond one\'s legal power or authority', 'An ultra vires act by a government agency is void and unenforceable', 140, 'master'),
  ('amicus curiae', 'LAW', 'A friend of the court offering expertise on matters of law', 'Amicus curiae briefs inform the court of broader implications of the case', 140, 'master'),
  ('estoppel', 'LAW', 'A bar to alleging or denying a fact because of previous conduct', 'Promissory estoppel prevents injustice when a party relies on another\'s representation', 140, 'master'),
  ('fiduciary', 'LAW', 'A relationship involving trust and confidence; duty to act in another\'s interest', 'A fiduciary duty requires placing the beneficiary\'s interests above one\'s own', 140, 'master'),
  ('tortious', 'LAW', 'Constituting or relating to a tort; a civil wrong', 'Tortious interference with contract requires intentional and improper conduct', 140, 'master'),
  ('adjudication', 'LAW', 'The formal judgment or decision of a court', 'Administrative adjudication applies agency expertise to specific factual disputes', 140, 'master'),
  ('precedent', 'LAW', 'A decided case that provides a basis for deciding subsequent cases', 'Binding precedent constrains lower courts within the same jurisdiction', 140, 'master'),
  ('litigant', 'LAW', 'A party engaged in a lawsuit', 'Both litigants bear the burden of presenting their case effectively', 140, 'master'),
  ('indemnity', 'LAW', 'Security against or compensation for damage, loss, or injury', 'A contractual indemnity clause allocates risk between the parties', 140, 'master'),
  ('sovereignty', 'LAW', 'Supreme authority within a territory; self-governance', 'State sovereignty under international law includes the right of non-intervention', 140, 'master'),
  ('injunction', 'LAW', 'A court order requiring or prohibiting a specific act', 'A preliminary injunction preserves the status quo pending full adjudication', 140, 'master'),
  ('remedy', 'LAW', 'The means by which a right is enforced or a wrong is redressed', 'Equitable remedies are available when monetary damages would be inadequate', 140, 'master'),
  ('doctrine', 'LAW', 'A principle or position in law', 'The doctrine of separation of powers distributes governmental authority among branches', 140, 'master'),
  ('ratification', 'LAW', 'Formal approval of an agreement or treaty', 'Treaty ratification binds the state under international law', 140, 'master'),
  ('equilibrium', 'ECON', 'A state where opposing economic forces are balanced', 'General equilibrium theory describes simultaneous clearing of all markets', 140, 'master'),
  ('externality', 'ECON', 'A cost or benefit affecting parties not directly involved in a transaction', 'Negative externalities justify regulatory intervention when private costs diverge from social costs', 140, 'master'),
  ('elasticity', 'ECON', 'The responsiveness of one economic variable to changes in another', 'Price elasticity of demand measures how quantity demanded responds to price changes', 140, 'master'),
  ('marginal utility', 'ECON', 'The additional satisfaction from consuming one more unit', 'Diminishing marginal utility explains why demand curves slope downward', 140, 'master'),
  ('Pareto optimal', 'ECON', 'A state where no one can be made better off without making another worse off', 'A Pareto optimal allocation is efficient but not necessarily equitable', 140, 'master'),
  ('moral hazard', 'ECON', 'Changed behavior when insulated from risk', 'Moral hazard arises when insurance reduces the insured party\'s incentive for careful behavior', 140, 'master'),
  ('adverse selection', 'ECON', 'Market distortion from asymmetric information before a transaction', 'Adverse selection in insurance markets drives healthy individuals out of the risk pool', 140, 'master'),
  ('oligopoly', 'ECON', 'A market dominated by a small number of large firms', 'Oligopolistic firms engage in strategic interaction, making game theory essential for analysis', 140, 'master'),
  ('monopsony', 'ECON', 'A market with only one buyer', 'Monopsony power in labor markets depresses wages below the marginal revenue product', 140, 'master'),
  ('liquidity', 'ECON', 'The ease with which an asset can be converted to cash', 'Central banks provide liquidity during financial crises to prevent systemic collapse', 140, 'master'),
  ('arbitrage', 'ECON', 'Profiting from price differences of the same asset in different markets', 'Arbitrage opportunities are quickly exploited, enforcing the law of one price', 140, 'master'),
  ('endogenous', 'ECON', 'Determined within the model; influenced by other variables in the system', 'Endogenous growth theory explains technological progress as resulting from economic incentives', 140, 'master'),
  ('exogenous', 'ECON', 'Determined outside the model; taken as given', 'An exogenous shock to oil supply propagates through the economy via input-output linkages', 140, 'master'),
  ('heteroskedasticity', 'ECON', 'Non-constant variance of error terms across observations', 'Heteroskedasticity biases standard errors, requiring robust estimation methods', 140, 'master'),
  ('autocorrelation', 'ECON', 'Correlation of a variable with its own lagged values', 'Autocorrelation in time series violates the independence assumption of ordinary least squares', 140, 'master'),
  ('Nash equilibrium', 'ECON', 'A strategy profile where no player benefits from unilateral deviation', 'In a Nash equilibrium, each player\'s strategy is a best response to the strategies of others', 140, 'master'),
  ('Bayesian', 'ECON', 'Relating to probability updating based on new evidence', 'Bayesian econometrics incorporates prior beliefs into parameter estimation', 140, 'master'),
  ('counterfactual', 'ECON', 'What would have happened in the absence of a treatment or policy', 'Causal inference requires constructing a credible counterfactual', 140, 'master'),
  ('deadweight loss', 'ECON', 'The loss of economic efficiency from market distortion', 'Taxation creates deadweight loss by driving a wedge between buyer and seller prices', 140, 'master'),
  ('rational expectations', 'ECON', 'The hypothesis that agents forecast optimally given available information', 'Under rational expectations, systematic monetary policy cannot affect real output', 140, 'master'),
  ('NP-complete', 'CS', 'A problem in NP to which all other NP problems can be reduced', 'Determining whether P equals NP is the central open problem in computational complexity', 140, 'master'),
  ('Turing-complete', 'CS', 'Capable of simulating any Turing machine; computationally universal', 'Any Turing-complete language can express any computable function', 140, 'master'),
  ('decidable', 'CS', 'Having an algorithm that always halts with a correct yes/no answer', 'The halting problem is the canonical example of an undecidable problem', 140, 'master'),
  ('polynomial time', 'CS', 'An algorithm whose running time is bounded by a polynomial in input size', 'Polynomial time algorithms are considered efficient; exponential ones are not', 140, 'master'),
  ('amortized', 'CS', 'Average cost per operation over a worst-case sequence of operations', 'Amortized analysis shows that dynamic array resizing costs O(1) per insertion on average', 140, 'master'),
  ('invariant', 'CS', 'A property that remains true throughout the execution of an algorithm', 'Loop invariants provide the basis for correctness proofs of iterative algorithms', 140, 'master'),
  ('idempotent', 'CS', 'An operation yielding the same result whether applied once or multiple times', 'Idempotent operations enable safe retry in distributed systems without duplicate effects', 140, 'master'),
  ('linearizable', 'CS', 'Appearing as if operations occurred atomically at some point in time', 'Linearizability is the gold standard for consistency in concurrent data structures', 140, 'master'),
  ('Byzantine fault', 'CS', 'An arbitrary or malicious failure in a distributed system', 'Byzantine fault tolerance requires at least 3f+1 nodes to tolerate f faulty nodes', 140, 'master'),
  ('consensus', 'CS', 'Agreement among distributed processes on a single value', 'The FLP impossibility result shows that consensus is impossible in asynchronous systems with even one crash', 140, 'master'),
  ('monotonic', 'CS', 'A property that once true remains true; never regresses', 'Monotonic reads guarantee a client never observes an earlier state after seeing a later one', 140, 'master'),
  ('confluent', 'CS', 'Producing the same result regardless of operation order', 'Confluent replicated data types guarantee convergence without coordination', 140, 'master'),
  ('quorum', 'CS', 'The minimum number of nodes that must participate for an operation to proceed', 'A read quorum overlapping with a write quorum ensures consistent reads', 140, 'master'),
  ('eventual consistency', 'CS', 'A guarantee that all replicas converge given sufficient time', 'Eventual consistency trades immediate agreement for availability and partition tolerance', 140, 'master'),
  ('CAP theorem', 'CS', 'A distributed system can provide at most two of consistency, availability, and partition tolerance', 'The CAP theorem forces fundamental tradeoffs in distributed system design', 140, 'master'),
  ('referential transparency', 'CS', 'An expression can be replaced by its value without changing program behavior', 'Referential transparency enables equational reasoning about program correctness', 140, 'master'),
  ('type safety', 'CS', 'A guarantee that well-typed programs cannot exhibit certain classes of errors', 'Strong type safety eliminates undefined behavior at compile time', 140, 'master'),
  ('Church-Turing thesis', 'CS', 'Any effectively calculable function is computable by a Turing machine', 'The Church-Turing thesis delineates the boundary of mechanical computation', 140, 'master'),
  ('lambda calculus', 'CS', 'A formal system for expressing computation based on function abstraction', 'The untyped lambda calculus is equivalent in power to a Turing machine', 140, 'master'),
  ('fixed point', 'CS', 'A value mapped to itself by a function; f(x) = x', 'Fixed point combinators enable recursion without explicit self-reference', 140, 'master'),
  ('morpheme', 'LING', 'The smallest meaningful unit of language', 'The word \'unhappiness\' contains three morphemes: un-, happy, -ness', 140, 'master'),
  ('phoneme', 'LING', 'The smallest unit of sound that distinguishes meaning', 'English distinguishes approximately 44 phonemes, though dialects vary', 140, 'master'),
  ('syntax', 'LING', 'The rules governing sentence structure', 'Chomsky\'s generative syntax posits innate universal grammar underlying all languages', 140, 'master'),
  ('pragmatics', 'LING', 'The study of language use in context', 'Pragmatics explains how speakers convey meaning beyond the literal content of their words', 140, 'master'),
  ('deixis', 'LING', 'Expression whose meaning depends on context (here, now, I, this)', 'Deictic expressions anchor utterances to the spatiotemporal context of their production', 140, 'master'),
  ('anaphora', 'LING', 'Use of a word referring back to a previous expression', 'Anaphoric reference requires the listener to resolve the antecedent from discourse context', 140, 'master'),
  ('performative', 'LING', 'An utterance that constitutes an action by being spoken', 'Performative speech acts like promising create obligations through their very utterance', 140, 'master'),
  ('illocutionary', 'LING', 'The intended force of a speech act', 'The illocutionary force of \'Can you pass the salt?\' is a request, not a question about ability', 140, 'master'),
  ('polysemy', 'LING', 'A single word having multiple related meanings', 'Polysemy presents challenges for natural language processing and lexicography', 140, 'master'),
  ('collocate', 'LING', 'A word that frequently appears alongside another', 'Strong collocations like \'heavy rain\' resist substitution by near-synonyms', 140, 'master'),
  ('morphological', 'LING', 'Relating to the form and structure of words', 'Morphological analysis reveals the internal complexity of seemingly simple words', 140, 'master'),
  ('prosody', 'LING', 'The rhythm, stress, and intonation patterns of speech', 'Prosodic cues disambiguate syntactically identical sentences with different meanings', 140, 'master'),
  ('grapheme', 'LING', 'The smallest unit of a writing system', 'The grapheme-phoneme correspondence in English is notoriously irregular', 140, 'master'),
  ('lexicon', 'LING', 'The complete set of words in a language; mental vocabulary', 'A speaker\'s productive lexicon is smaller than their receptive lexicon', 140, 'master'),
  ('idiolect', 'LING', 'An individual\'s unique language variety', 'Every speaker\'s idiolect reflects their personal history of linguistic experience', 140, 'master'),
  ('creole', 'LING', 'A stable language developed from a mixture of languages', 'Creole languages exhibit systematic grammar, not mere simplification of the source languages', 140, 'master'),
  ('sociolect', 'LING', 'A variety of language associated with a social group', 'Professional sociolects serve both communicative efficiency and group identity', 140, 'master'),
  ('diglossia', 'LING', 'A situation where two varieties of a language coexist with different functions', 'Diglossia maintains a high variety for formal contexts and a low variety for everyday use', 140, 'master'),
  ('code-switching', 'LING', 'Alternating between languages or language varieties in discourse', 'Code-switching demonstrates bilingual competence rather than deficiency', 140, 'master'),
  ('univeral grammar', 'LING', 'The hypothesized innate language faculty common to all humans', 'Universal grammar constrains the hypothesis space children explore during language acquisition', 140, 'master'),
  ('metacognition', 'PSY', 'Thinking about one\'s own thinking; awareness of cognitive processes', 'Metacognitive monitoring enables learners to identify gaps in their understanding', 140, 'master'),
  ('heuristic', 'PSY', 'A mental shortcut for efficient but potentially biased judgment', 'Availability heuristic causes overestimation of vivid or recent events', 140, 'master'),
  ('cognitive dissonance', 'PSY', 'Psychological discomfort from holding contradictory beliefs simultaneously', 'Cognitive dissonance motivates belief change, rationalization, or selective attention', 140, 'master'),
  ('self-efficacy', 'PSY', 'Belief in one\'s capacity to execute behaviors necessary to achieve goals', 'Self-efficacy mediates the relationship between knowledge and performance', 140, 'master'),
  ('working memory', 'PSY', 'The limited-capacity system for temporary maintenance and manipulation of information', 'Working memory capacity predicts performance across diverse cognitive tasks', 140, 'master'),
  ('executive function', 'PSY', 'Higher-order cognitive processes governing planning, inhibition, and flexibility', 'Executive function develops throughout childhood and declines in certain neurodegenerative conditions', 140, 'master'),
  ('priming', 'PSY', 'Exposure to one stimulus influencing response to a subsequent stimulus', 'Semantic priming reveals the associative structure of the mental lexicon', 140, 'master'),
  ('schema', 'PSY', 'An organized mental framework for understanding categories of information', 'Schemas facilitate rapid comprehension but can introduce systematic distortions', 140, 'master'),
  ('automaticity', 'PSY', 'Performance of cognitive tasks without conscious attention', 'Automaticity develops through extensive practice, freeing attentional resources for novel demands', 140, 'master'),
  ('habituation', 'PSY', 'Decreased responsiveness to repeated stimulation', 'Habituation paradigms reveal perceptual discrimination in preverbal infants', 140, 'master'),
  ('neurogenesis', 'PSY', 'The formation of new neurons in the brain', 'Adult hippocampal neurogenesis may contribute to learning and emotional regulation', 140, 'master'),
  ('lateralization', 'PSY', 'Functional specialization of the brain\'s hemispheres', 'Language lateralization to the left hemisphere is typical but not universal', 140, 'master'),
  ('attachment', 'PSY', 'The emotional bond between infant and caregiver', 'Secure attachment predicts better emotional regulation and social competence in later development', 140, 'master'),
  ('operant conditioning', 'PSY', 'Learning through consequences of behavior', 'Operant conditioning shapes behavior through reinforcement schedules and contingencies', 140, 'master'),
  ('implicit memory', 'PSY', 'Unconscious memory influencing behavior without awareness', 'Implicit memory systems preserve information that explicit recall cannot access', 140, 'master'),
  ('confabulation', 'PSY', 'The production of fabricated memories without intention to deceive', 'Confabulation reveals the constructive nature of memory retrieval', 140, 'master'),
  ('dissociation', 'PSY', 'A disconnection between mental processes normally integrated', 'Dissociative states can result from trauma as a protective mechanism', 140, 'master'),
  ('resilience', 'PSY', 'The capacity to recover from adversity and maintain function', 'Psychological resilience involves adaptive coping, social support, and meaning-making', 140, 'master'),
  ('individuation', 'PSY', 'The process of becoming a distinct individual; psychological differentiation', 'Individuation involves integrating conscious and unconscious aspects of the self', 140, 'master'),
  ('catharsis', 'PSY', 'Emotional release providing relief from repressed feelings', 'The cathartic model of emotional expression has been largely superseded by process models', 140, 'master'),
  ('homeostasis', 'BIO', 'The maintenance of stable internal conditions in a biological system', 'Homeostatic mechanisms regulate temperature, pH, and osmolarity within narrow limits', 140, 'master'),
  ('phylogenetic', 'BIO', 'Relating to evolutionary relationships among organisms', 'Phylogenetic trees represent hypotheses about the evolutionary history of taxa', 140, 'master'),
  ('symbiosis', 'BIO', 'Close and long-term biological interaction between different species', 'Mutualistic symbiosis provides fitness benefits to both interacting species', 140, 'master'),
  ('allosteric', 'BIO', 'Regulation of an enzyme by binding at a site other than the active site', 'Allosteric regulation enables rapid metabolic control without changes in gene expression', 140, 'master'),
  ('transcription', 'BIO', 'The synthesis of RNA from a DNA template', 'Transcription factors bind regulatory sequences to activate or repress gene expression', 140, 'master'),
  ('translation', 'BIO', 'The synthesis of protein from an mRNA template', 'Ribosomal translation proceeds through initiation, elongation, and termination phases', 140, 'master'),
  ('mitochondrial', 'BIO', 'Relating to the cell\'s energy-producing organelles', 'Mitochondrial dysfunction contributes to aging and neurodegenerative disease', 140, 'master'),
  ('endosymbiotic', 'BIO', 'Relating to the theory that organelles evolved from engulfed prokaryotes', 'Endosymbiotic origin explains why mitochondria and chloroplasts retain their own DNA', 140, 'master'),
  ('pleiotropy', 'BIO', 'A single gene influencing multiple seemingly unrelated phenotypic traits', 'Pleiotropy constrains evolutionary adaptation because changes affect multiple functions', 140, 'master'),
  ('epistasis', 'BIO', 'Gene interaction where one gene modifies the effect of another', 'Epistatic interactions complicate the prediction of phenotype from genotype', 140, 'master'),
  ('phenotypic plasticity', 'BIO', 'The ability of one genotype to produce different phenotypes in different environments', 'Phenotypic plasticity allows organisms to respond adaptively to environmental variation', 140, 'master'),
  ('speciation', 'BIO', 'The evolutionary process by which new species arise', 'Allopatric speciation occurs when geographic barriers isolate populations', 140, 'master'),
  ('genetic drift', 'BIO', 'Random changes in allele frequency due to sampling effects in finite populations', 'Genetic drift is especially powerful in small populations where chance dominates selection', 140, 'master'),
  ('horizontal gene transfer', 'BIO', 'Transfer of genetic material between organisms other than parent to offspring', 'Horizontal gene transfer in bacteria enables rapid spread of antibiotic resistance', 140, 'master'),
  ('quorum sensing', 'BIO', 'Bacterial communication through signaling molecules to coordinate behavior', 'Quorum sensing regulates biofilm formation, virulence factor expression, and bioluminescence', 140, 'master'),
  ('trophic cascade', 'BIO', 'Indirect effects flowing through food web levels', 'Reintroduction of wolves in Yellowstone triggered a trophic cascade restoring riparian vegetation', 140, 'master'),
  ('niche construction', 'BIO', 'Organisms modifying their environment in ways that affect selection pressures', 'Niche construction creates evolutionary feedback between organisms and their environments', 140, 'master'),
  ('emergent property', 'BIO', 'A property arising from interactions among simpler components', 'Consciousness may be an emergent property of neural network complexity', 140, 'master'),
  ('redox', 'BIO', 'A chemical reaction involving transfer of electrons between molecules', 'Cellular respiration is a series of redox reactions extracting energy from glucose', 140, 'master'),
  ('chemotaxis', 'BIO', 'Movement of an organism in response to a chemical stimulus', 'Bacterial chemotaxis involves flagellar switching guided by receptor methylation', 140, 'master'),
  ('impedance', 'ENG', 'Opposition to alternating current flow; generalization of resistance', 'Impedance matching maximizes power transfer between source and load', 140, 'master'),
  ('resonance', 'ENG', 'Amplified response at a system\'s natural frequency', 'Structural resonance under periodic loading can cause catastrophic failure', 140, 'master'),
  ('feedback loop', 'ENG', 'A signal path where output influences input', 'Negative feedback stabilizes systems; positive feedback drives them to extremes', 140, 'master'),
  ('damping', 'ENG', 'Dissipation of energy from an oscillating system', 'Critical damping returns a system to equilibrium in minimum time without oscillation', 140, 'master'),
  ('hysteresis', 'ENG', 'Dependence of system state on its history, not just current input', 'Magnetic hysteresis causes energy loss in transformer cores during AC cycles', 140, 'master'),
  ('latency', 'ENG', 'Time delay between stimulus and response in a system', 'Tail latency at the 99th percentile determines user-perceived system responsiveness', 140, 'master'),
  ('throughput', 'ENG', 'The rate at which a system processes or transmits data', 'Throughput optimization often conflicts with latency minimization', 140, 'master'),
  ('bandwidth', 'ENG', 'The range of frequencies or data rate a channel can support', 'Shannon\'s theorem gives the maximum information rate for a noisy channel of given bandwidth', 140, 'master'),
  ('signal-to-noise ratio', 'ENG', 'The ratio of useful information to background interference', 'A higher signal-to-noise ratio enables more reliable communication and detection', 140, 'master'),
  ('modular', 'ENG', 'Composed of separable, interchangeable components with defined interfaces', 'Modular architecture enables independent development, testing, and replacement of components', 140, 'master'),
  ('fault tolerance', 'ENG', 'The ability to continue operating despite component failures', 'Fault tolerance through redundancy is essential for safety-critical systems', 140, 'master'),
  ('deterministic', 'ENG', 'Producing the same output for a given input without random variation', 'Deterministic systems enable reproducibility and formal verification', 140, 'master'),
  ('non-deterministic', 'ENG', 'Having outcomes that depend on factors not captured by the input alone', 'Non-deterministic scheduling in concurrent systems makes reasoning about correctness difficult', 140, 'master'),
  ('load balancing', 'ENG', 'Distributing work across multiple resources to optimize utilization', 'Consistent hashing provides load balancing that minimizes redistribution on node changes', 140, 'master'),
  ('debounce', 'ENG', 'Filtering rapid repeated signals to prevent multiple triggers', 'Switch debouncing eliminates spurious transitions caused by mechanical contact bounce', 140, 'master'),
  ('transient', 'ENG', 'A temporary state or signal before steady-state is reached', 'Transient analysis determines how quickly a circuit reaches its final operating point', 140, 'master'),
  ('steady state', 'ENG', 'The long-term behavior of a system after transients have decayed', 'Steady state analysis assumes all initial conditions have become irrelevant', 140, 'master'),
  ('thermal', 'ENG', 'Relating to heat and temperature in engineering systems', 'Thermal management in integrated circuits limits clock speeds and device density', 140, 'master'),
  ('creep', 'ENG', 'Slow permanent deformation of material under sustained stress', 'Creep in turbine blades limits the operating temperature and lifetime of jet engines', 140, 'master'),
  ('fatigue', 'ENG', 'Progressive structural damage from repeated cyclic loading', 'Metal fatigue caused by vibration is a primary concern in aircraft structural design', 140, 'master'),
  ('catalysis', 'CHEM', 'Acceleration of a chemical reaction by a substance not consumed in the process', 'Enzymatic catalysis lowers activation energy by stabilizing the transition state', 140, 'master'),
  ('stereoisomer', 'CHEM', 'Molecules with the same connectivity but different spatial arrangement', 'Biological systems typically produce and respond to only one stereoisomer of a chiral molecule', 140, 'master'),
  ('chiral', 'CHEM', 'Not superimposable on its mirror image; having handedness', 'Chirality in drug molecules can mean the difference between therapeutic effect and toxicity', 140, 'master'),
  ('stoichiometric', 'CHEM', 'Relating to the exact proportions of reactants and products', 'Stoichiometric calculations ensure correct reagent quantities for complete reaction', 140, 'master'),
  ('thermodynamic', 'CHEM', 'Relating to energy transformations and spontaneity', 'Thermodynamic favorability determines whether a reaction can proceed spontaneously', 140, 'master'),
  ('kinetic', 'CHEM', 'Relating to the rate and mechanism of chemical reactions', 'Kinetic control yields the fastest-formed product; thermodynamic control yields the most stable', 140, 'master'),
  ('equilibrium constant', 'CHEM', 'The ratio of product to reactant concentrations at equilibrium', 'The equilibrium constant quantifies the extent to which a reaction favors products', 140, 'master'),
  ('oxidation state', 'CHEM', 'The degree of oxidation of an atom in a chemical compound', 'Tracking oxidation state changes reveals electron transfer in redox reactions', 140, 'master'),
  ('electronegativity', 'CHEM', 'An atom\'s tendency to attract shared electrons', 'Electronegativity differences between bonded atoms determine bond polarity', 140, 'master'),
  ('conjugation', 'CHEM', 'Alternating single and double bonds enabling electron delocalization', 'Conjugation stabilizes molecules and explains the color of many organic dyes', 140, 'master'),
  ('nucleophile', 'CHEM', 'An electron-rich species that donates electrons to form bonds', 'Nucleophilic attack on electrophilic carbon is the fundamental step in many organic reactions', 140, 'master'),
  ('electrophile', 'CHEM', 'An electron-poor species that accepts electrons', 'Electrophilic aromatic substitution preserves the stability of the aromatic ring', 140, 'master'),
  ('polymerization', 'CHEM', 'The process of combining monomers into a long-chain molecule', 'Controlled polymerization enables precise molecular weight and architecture', 140, 'master'),
  ('crystallographic', 'CHEM', 'Relating to the study of crystal structure by diffraction methods', 'X-ray crystallography reveals atomic positions within a crystal lattice', 140, 'master'),
  ('spectroscopic', 'CHEM', 'Relating to measurement of interaction between matter and electromagnetic radiation', 'Spectroscopic techniques identify functional groups and molecular connectivity', 140, 'master'),
  ('beneficence', 'ETHIC', 'The ethical obligation to do good and promote well-being', 'Medical beneficence requires balancing potential benefits against risks to the patient', 140, 'master'),
  ('non-maleficence', 'ETHIC', 'The ethical principle of doing no harm', 'Non-maleficence is the foundational constraint: first, do no harm', 140, 'master'),
  ('autonomy', 'ETHIC', 'Self-governance; the right to make decisions about one\'s own life', 'Respect for autonomy requires informed consent before any medical intervention', 140, 'master'),
  ('justice', 'ETHIC', 'Fair distribution of benefits, risks, and costs', 'Distributive justice asks how resources should be allocated among competing claims', 140, 'master'),
  ('dignity', 'ETHIC', 'Inherent worth deserving of respect regardless of utility', 'Human dignity is unconditional and cannot be forfeited by circumstance or conduct', 140, 'master'),
  ('integrity', 'ETHIC', 'Wholeness and coherence of moral character; adherence to principles', 'Professional integrity demands consistency between stated values and actual practice', 140, 'master'),
  ('compassion', 'ETHIC', 'Deep awareness of suffering coupled with the wish to relieve it', 'Compassion without competence cannot help; competence without compassion will not try', 140, 'master'),
  ('stewardship', 'ETHIC', 'Responsible management of resources entrusted to one\'s care', 'Environmental stewardship recognizes our obligation to future generations', 140, 'master'),
  ('reciprocity', 'ETHIC', 'Mutual exchange of benefits; balanced give and take', 'Ethical reciprocity extends beyond tit-for-tat to encompass generalized goodwill', 140, 'master'),
  ('solidarity', 'ETHIC', 'Unity and mutual support within a group sharing common interests', 'Solidarity acknowledges that individual flourishing depends on collective well-being', 140, 'master'),
  ('prudence', 'ETHIC', 'Practical wisdom in discerning the best course of action', 'Prudence weighs consequences, context, and principle to navigate moral complexity', 140, 'master'),
  ('magnanimity', 'ETHIC', 'Generosity of spirit; nobility in giving and forgiving', 'Magnanimity expresses strength through generosity rather than through domination', 140, 'master'),
  ('temperance', 'ETHIC', 'Self-restraint and moderation in action and appetite', 'Temperance is not deprivation but the disciplined direction of desire toward worthy ends', 140, 'master'),
  ('fortitude', 'ETHIC', 'Courage and strength in facing difficulty or adversity', 'Fortitude enables perseverance when the right path is also the difficult one', 140, 'master'),
  ('veracity', 'ETHIC', 'Habitual truthfulness; devotion to truth', 'Veracity in professional life builds the trust on which all cooperation depends', 140, 'master'),
  ('fidelity', 'ETHIC', 'Faithfulness to obligations, promises, and relationships', 'Fidelity to one\'s word is the foundation of all contractual and personal bonds', 140, 'master'),
  ('supererogatory', 'ETHIC', 'Beyond what is morally required; above the call of duty', 'Supererogatory acts inspire admiration without creating obligation in others', 140, 'master'),
  ('categorical imperative', 'ETHIC', 'An unconditional moral obligation binding regardless of desire', 'The categorical imperative demands: act only on maxims you could will as universal law', 140, 'master'),
  ('virtue', 'ETHIC', 'A stable character disposition toward morally excellent action', 'Virtue is acquired through practice and becomes second nature through habituation', 140, 'master'),
  ('care', 'ETHIC', 'Attentive responsiveness to the needs of those dependent on us', 'An ethic of care emphasizes relationship, responsibility, and attentiveness to particular others', 140, 'master');

-- ============================================================
-- Grant Dave access
-- ============================================================

GRANT SELECT, INSERT, UPDATE ON dave_kb.vocabulary TO 'dave_ai'@'localhost';
GRANT SELECT, INSERT, UPDATE ON dave_kb.vocabulary_metadata TO 'dave_ai'@'localhost';
FLUSH PRIVILEGES;
