#!/bin/bash
# ============================================================================
# NWE Website Generator — Skeleton Builder
# Generates a complete BMA-style JSP servlet website from a subject definition.
#
# Creates: JSP pages, CSS, JS, CD1 connectors, status page with port indicators,
# deploy scripts, db.properties template, and SQL schema from nouns/objects.
#
# Usage:
#   bash scripts/generate-website.sh <module-name> <config-file>
#   bash scripts/generate-website.sh MyModule scripts/website-subjects/mymodule.xml
#
# The config file (XML) defines:
#   - Module name, color, ports, database
#   - Content headers (page names)
#   - Nouns/objects (become DB tables and JSP data pages)
#   - Port assignments per page
#
# Lookup scripts (run before this to discover nouns):
#   bash scripts/discover-subjects.sh <source-dir>  → generates subject XML
#
# Author: Max Rupplin — MEARVK LLC
# DIGTIK: SecurityHeadersFilter, PreparedStatement, 44px tap targets, CD1
# ============================================================================



SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# ─── Argument Parsing ───
MODULE_NAME="${1:-NewModule}"
CONFIG_FILE="${2:-}"

if [ -z "$CONFIG_FILE" ] || [ ! -f "$CONFIG_FILE" ]; then
    echo "═══════════════════════════════════════════════════════════════"
    echo " NWE Website Generator"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo " Usage: bash scripts/generate-website.sh <module-name> <config.xml>"
    echo ""
    echo " Config XML format:"
    echo '   <website-config>'
    echo '     <module name="MyModule" color="#3b82f6" database="nwe_mymodule"/>'
    echo '     <ports start="19000" end="19007"/>'
    echo '     <pages>'
    echo '       <page name="Overview" file="index" default="true"/>'
    echo '       <page name="Data" file="data" port="19000"/>'
    echo '       <page name="Reports" file="reports" port="19001"/>'
    echo '       <page name="Status" file="status"/>'
    echo '     </pages>'
    echo '     <nouns>'
    echo '       <noun name="records" table="module_records" columns="id,title,category,value,created_at"/>'
    echo '       <noun name="sources" table="module_sources" columns="id,name,url,type,active"/>'
    echo '     </nouns>'
    echo '   </website-config>'
    echo ""
    echo " Generate a config from existing data:"
    echo "   bash scripts/discover-subjects.sh <source-dir>"
    echo ""
    exit 1
fi

# ─── Parse Config (simple grep-based, no external XML tools needed) ───
MODULE_COLOR=$(grep -oP 'color="\K[^"]+' "$CONFIG_FILE" | head -1)
MODULE_DB=$(grep -oP 'database="\K[^"]+' "$CONFIG_FILE" | head -1)
PORT_START=$(grep -oP 'start="\K[^"]+' "$CONFIG_FILE" | head -1)
PORT_END=$(grep -oP 'end="\K[^"]+' "$CONFIG_FILE" | head -1)
MODULE_COLOR="${MODULE_COLOR:-#3b82f6}"
MODULE_DB="${MODULE_DB:-nwe_${MODULE_NAME,,}}"
PORT_START="${PORT_START:-19000}"
PORT_END="${PORT_END:-19007}"

# Extract pages
PAGES=()
PAGE_FILES=()
PAGE_PORTS=()
while IFS= read -r line; do
    pname=$(echo "$line" | grep -oP 'name="\K[^"]+')
    pfile=$(echo "$line" | grep -oP 'file="\K[^"]+')
    pport=$(echo "$line" | grep -oP 'port="\K[^"]+')
    [ -n "$pname" ] && PAGES+=("$pname") && PAGE_FILES+=("$pfile") && PAGE_PORTS+=("${pport:-0}")
done < <(grep '<page ' "$CONFIG_FILE")

# Extract nouns
NOUNS=()
NOUN_TABLES=()
NOUN_COLUMNS=()
while IFS= read -r line; do
    nname=$(echo "$line" | grep -oP 'name="\K[^"]+')
    ntable=$(echo "$line" | grep -oP 'table="\K[^"]+')
    ncols=$(echo "$line" | grep -oP 'columns="\K[^"]+')
    [ -n "$nname" ] && NOUNS+=("$nname") && NOUN_TABLES+=("$ntable") && NOUN_COLUMNS+=("$ncols")
done < <(grep '<noun ' "$CONFIG_FILE")

# ─── Output Directories ───
OUT_DIR="$PROJECT_ROOT/generated/$MODULE_NAME"
WEBAPP_DIR="$OUT_DIR/servlets/servlet/src/main/webapp"
SMART_DIR="$OUT_DIR/smartphone"
INSTALL_DIR="$OUT_DIR/install"

echo "═══════════════════════════════════════════════════════════════"
echo " NWE Website Generator"
echo " Module:   $MODULE_NAME"
echo " Color:    $MODULE_COLOR"
echo " Database: $MODULE_DB"
echo " Ports:    $PORT_START–$PORT_END"
echo " Pages:    ${#PAGES[@]}"
echo " Nouns:    ${#NOUNS[@]}"
echo " Output:   $OUT_DIR"
echo "═══════════════════════════════════════════════════════════════"
echo ""

mkdir -p "$WEBAPP_DIR/WEB-INF/lib" "$WEBAPP_DIR/css" "$WEBAPP_DIR/js" "$WEBAPP_DIR/images" "$WEBAPP_DIR/sql"
mkdir -p "$SMART_DIR/css" "$SMART_DIR/js"
mkdir -p "$INSTALL_DIR"

# ============================================================================
# GENERATE: CSS
# ============================================================================
echo "[1] Generating CSS..."

cat > "$WEBAPP_DIR/css/style.css" << EOF
/* ${MODULE_NAME}™ — Generated by NWE Website Generator */
:root {
    --bg-dark: #0a0a0f;
    --bg-section: #111118;
    --bg-card: #1a1a24;
    --text-primary: #ffffff;
    --text-secondary: #a1a1aa;
    --text-muted: #71717a;
    --accent: ${MODULE_COLOR};
    --accent-hover: ${MODULE_COLOR}cc;
    --border: #27272a;
    --radius: 8px;
    --radius-lg: 12px;
    --max-width: 1200px;
    --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    --font-mono: 'JetBrains Mono', 'Fira Code', monospace;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: var(--font); background: var(--bg-dark); color: var(--text-primary); line-height: 1.6; -webkit-font-smoothing: antialiased; }
.nav { background: var(--bg-dark); border-bottom: 1px solid var(--border); padding: 0.75rem 2rem; display: flex; align-items: center; position: sticky; top: 0; z-index: 100; }
.nav-inner { max-width: var(--max-width); margin: 0 auto; display: flex; align-items: center; width: 100%; }
.nav-brand { font-weight: 700; color: var(--text-primary); text-decoration: none; display: flex; align-items: center; gap: 0.5rem; }
.nav-links { display: flex; list-style: none; gap: 0.25rem; margin-left: 2rem; }
.nav-links a { color: var(--text-secondary); text-decoration: none; padding: 0.5rem 0.75rem; border-radius: var(--radius); font-size: 0.85rem; }
.nav-links a:hover, .nav-links a.active { color: var(--text-primary); background: var(--bg-card); }
.nav-actions { margin-left: auto; display: flex; gap: 0.5rem; }
.nav-cta { color: var(--accent); text-decoration: none; font-size: 0.85rem; padding: 0.4rem 0.75rem; border: 1px solid var(--border); border-radius: var(--radius); }
.hero { padding: 5rem 2rem; text-align: center; }
.hero-inner { max-width: 720px; margin: 0 auto; }
.hero-tag { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; color: var(--accent); }
.hero h1 { font-size: 3rem; font-weight: 800; margin: 0.5rem 0; }
.hero p { font-size: 1.1rem; color: var(--text-secondary); }
.section { padding: 5rem 2rem; border-top: 1px solid var(--border); }
.section-inner { max-width: var(--max-width); margin: 0 auto; }
.section h2 { font-size: 1.75rem; font-weight: 700; margin-bottom: 0.5rem; }
.section p { color: var(--text-secondary); margin-bottom: 1rem; }
.table-wrap { overflow-x: auto; margin: 1rem 0; border-radius: var(--radius); border: 1px solid var(--border); }
table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
th { background: var(--bg-card); color: var(--text-muted); font-weight: 600; text-align: left; padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }
td { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }
/* Port status indicators */
.port-dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 6px; }
.port-green { background: #22c55e; box-shadow: 0 0 6px #22c55e; }
.port-yellow { background: #eab308; box-shadow: 0 0 6px #eab308; }
.port-red { background: #ef4444; box-shadow: 0 0 6px #ef4444; }
@media (max-width: 768px) { .nav-links { display: none; } .hero { padding: 4rem 1.5rem; } .section { padding: 3rem 1.5rem; } }
EOF

# ============================================================================
# GENERATE: JS (CD1 + port status)
# ============================================================================
echo "[2] Generating JS..."

cat > "$WEBAPP_DIR/js/connector.js" << 'EOF'
(function(){
    var btn=document.getElementById("cd1-btn");
    var dialog=document.getElementById("cd1-dialog");
    var overlay=document.getElementById("cd1-overlay");
    if(!btn||!dialog||!overlay)return;
    btn.addEventListener("click",function(){
        if(dialog.style.display==="block"){dialog.style.display="none";overlay.style.display="none";btn.style.transform="";btn.style.filter="";return;}
        btn.style.transform="scale(0.9)";btn.style.filter="drop-shadow(0 0 8px var(--accent,#3b82f6))";
        setTimeout(function(){btn.style.transform="";btn.style.filter="";dialog.style.display="block";overlay.style.display="block";},750);
    });
    overlay.addEventListener("click",function(){dialog.style.display="none";overlay.style.display="none";});
    // Restore saved port/role
    var sp=localStorage.getItem("nwe-port"),sr=localStorage.getItem("nwe-role");
    if(sp){var p=document.getElementById("cd1-port");if(p)p.value=sp;}
    if(sr){var r=document.getElementById("cd1-role");if(r)r.value=sr;}
})();
function cd1Send(){
    var s=document.getElementById("cd1-action"),t=document.getElementById("cd1-textarea");
    var portEl=document.getElementById("cd1-port"),roleEl=document.getElementById("cd1-role");
    if(!s||!t)return;
    var action=s.value,ts=new Date().toLocaleTimeString();
    var port=portEl?portEl.value:"19000",role=roleEl?roleEl.value:"guest";
    var msg="";
    switch(action){
        case"setport":msg="["+ts+"] SET PORT|"+port+" — Routed\n";break;
        case"unsetport":msg="["+ts+"] UNSET PORT|"+port+" — Disconnected\n";break;
        case"saveconfig":localStorage.setItem("nwe-port",port);localStorage.setItem("nwe-role",role);msg="["+ts+"] SAVE|port="+port+"|role="+role+" — Saved\n";break;
        case"connect":msg="["+ts+"] Connecting to port "+port+"...\n["+ts+"] Connected.\n";break;
        case"disconnect":msg="["+ts+"] Disconnecting...\n["+ts+"] Disconnected.\n";break;
        case"status":msg="["+ts+"] STATUS|port="+port+"|OK\n";break;
        default:msg="["+ts+"] "+action+" sent to port "+port+".\n";
    }
    t.value+=msg;t.scrollTop=t.scrollHeight;
}
function cd1Ok(){var t=document.getElementById("cd1-textarea");if(!t)return;t.value+="["+new Date().toLocaleTimeString()+"] OK.\n";t.scrollTop=t.scrollHeight;}
EOF

# ============================================================================
# GENERATE: Status page with port indicators (green/yellow/red)
# ============================================================================
echo "[3] Generating status.jsp with port indicators..."

PORT_SEQ=$(seq -s, $PORT_START $PORT_END)

# Build port rows
PORT_ROWS=""
PORT_NUM=$PORT_START
for i in "${!PAGES[@]}"; do
    p="${PAGE_PORTS[$i]}"
    if [ "$p" != "0" ] && [ -n "$p" ]; then
        PORT_ROWS+="                    <tr><td><span class=\"port-dot\" id=\"dot-${p}\"></span>${PAGES[$i]}</td><td>${p}</td><td id=\"status-${p}\">Checking...</td></tr>\n"
    fi
done

cat > "$WEBAPP_DIR/status.jsp" << STATUSEOF
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.sql.*, java.util.Properties, java.io.InputStream, java.net.Socket" %>
<%
    // GitHub authorization check
    boolean authorized = false;
    try { java.net.HttpURLConnection hc = (java.net.HttpURLConnection) new java.net.URL("https://raw.githubusercontent.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/main/psychiatry/secrets/public.key").openConnection(); hc.setRequestMethod("HEAD"); hc.setConnectTimeout(5000); authorized = (hc.getResponseCode() == 200); hc.disconnect(); } catch (Exception e) {}

    // Check admin session
    boolean isAdmin = "admin".equals(session.getAttribute("bma-role"));

    // DB check
    String dbStatus = "Offline"; String dbVersion = "";
    Properties dbProps = new Properties();
    try {
        InputStream dbIn = application.getResourceAsStream("/WEB-INF/db.properties");
        if (dbIn != null) { dbProps.load(dbIn); dbIn.close(); }
        Class.forName(dbProps.getProperty("db.driver", "com.mysql.cj.jdbc.Driver"));
        Connection conn = DriverManager.getConnection(dbProps.getProperty("db.url"), dbProps.getProperty("db.user"), dbProps.getProperty("db.password"));
        dbStatus = "Online"; dbVersion = conn.getMetaData().getDatabaseProductVersion(); conn.close();
    } catch (Exception e) { dbStatus = "Error"; }

    // Port checks
    int[] ports = {${PORT_SEQ}};
    String[] portStatus = new String[ports.length];
    for (int i = 0; i < ports.length; i++) {
        try { Socket s = new Socket(); s.connect(new java.net.InetSocketAddress("127.0.0.1", ports[i]), 500); s.close(); portStatus[i] = "connected"; }
        catch (Exception e) { portStatus[i] = "offline"; }
    }
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Status — ${MODULE_NAME}™</title>
    <link rel="stylesheet" href="css/style.css"/>
</head>
<body>
<nav class="nav"><div class="nav-inner">
    <a href="index.jsp" class="nav-brand">${MODULE_NAME}™</a>
    <ul class="nav-links">
$(for i in "${!PAGES[@]}"; do echo "        <li><a href=\"${PAGE_FILES[$i]}.jsp\"$([ "${PAGE_FILES[$i]}" = "status" ] && echo ' class="active"')>${PAGES[$i]}</a></li>"; done)
    </ul>
</div></nav>

<section class="hero" style="padding:4rem 2rem;">
    <div class="hero-inner"><span class="hero-tag">System Health</span><h1>Status</h1></div>
</section>

<section class="section">
    <div class="section-inner">
        <h2>Port Status</h2>
        <p>Green = connected, Yellow = admin active, Red = offline</p>
        <div class="table-wrap">
            <table>
                <thead><tr><th>Service</th><th>Port</th><th>Status</th></tr></thead>
                <tbody>
<% for (int i = 0; i < ports.length; i++) {
    String color = "red";
    String label = "Offline";
    if ("connected".equals(portStatus[i])) { color = isAdmin ? "yellow" : "green"; label = isAdmin ? "Admin" : "Connected"; }
%>
                    <tr><td><span class="port-dot port-<%= color %>"></span>Port <%= ports[i] %></td><td><%= ports[i] %></td><td><%= label %></td></tr>
<% } %>
                </tbody>
            </table>
        </div>
        <h2 style="margin-top:2rem;">Database</h2>
        <div class="table-wrap">
            <table>
                <thead><tr><th>Service</th><th>Status</th><th>Version</th></tr></thead>
                <tbody>
                    <tr><td><span class="port-dot port-<%= "Online".equals(dbStatus) ? "green" : "red" %>"></span>MySQL (${MODULE_DB})</td><td><%= dbStatus %></td><td><%= dbVersion %></td></tr>
                    <tr><td><span class="port-dot port-green"></span>Servlet Container</td><td>Online</td><td><%= application.getServerInfo() %></td></tr>
                    <tr><td><span class="port-dot port-green"></span>JVM</td><td>Online</td><td><%= System.getProperty("java.version") %></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<script src="js/connector.js"></script>
</body>
</html>
STATUSEOF

# ============================================================================
# GENERATE: Index page
# ============================================================================
echo "[4] Generating index.jsp..."

NAV_LINKS=""
for i in "${!PAGES[@]}"; do
    NAV_LINKS+="        <li><a href=\"${PAGE_FILES[$i]}.jsp\">${PAGES[$i]}</a></li>\n"
done

cat > "$WEBAPP_DIR/index.jsp" << INDEXEOF
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.net.*" %>
<%
    boolean authorized = false;
    try { HttpURLConnection hc = (HttpURLConnection) new URL("https://raw.githubusercontent.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/main/psychiatry/secrets/public.key").openConnection(); hc.setRequestMethod("HEAD"); hc.setConnectTimeout(5000); authorized = (hc.getResponseCode() == 200); hc.disconnect(); } catch (Exception e) {}
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>${MODULE_NAME}™</title>
    <link rel="stylesheet" href="css/style.css"/>
</head>
<body>
<nav class="nav"><div class="nav-inner">
    <a href="index.jsp" class="nav-brand">${MODULE_NAME}™</a>
    <ul class="nav-links">
$(echo -e "$NAV_LINKS")
    </ul>
    <div class="nav-actions"><a href="settings.jsp" class="nav-cta">Settings</a></div>
</div></nav>

<section class="hero">
    <div class="hero-inner">
        <span class="hero-tag">MEARVK LLC</span>
        <h1>${MODULE_NAME}™</h1>
        <p>Auto-generated NWE servlet module. Ports ${PORT_START}–${PORT_END}.</p>
    </div>
</section>

<!-- CD1 Connector -->
<div style="display:flex;justify-content:center;padding:2rem 0;">
    <button id="cd1-btn" style="all:unset;cursor:pointer;"><img src="images/black.button.png" alt="CD1" style="width:80px;height:80px;border-radius:50%;"/></button>
</div>
<div id="cd1-overlay" style="display:none;position:fixed;inset:0;z-index:299;"></div>
<div id="cd1-dialog" style="display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:300;background:#111118;border:1px solid #27272a;border-radius:12px;padding:1.25rem;width:560px;max-width:90vw;box-shadow:0 8px 32px rgba(0,0,0,0.6);">
    <div style="font-size:0.9rem;font-weight:600;color:#fff;margin-bottom:0.75rem;">${MODULE_NAME}™ Connector</div>
    <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-bottom:0.75rem;">
        <select id="cd1-action" style="background:#1a1a24;color:#fff;border:1px solid #27272a;border-radius:8px;padding:0.45rem 0.75rem;font-size:0.8rem;">
            <option value="connect">Connect</option><option value="disconnect">Disconnect</option><option value="status">Status</option>
            <option value="setport">Set Port</option><option value="unsetport">Unset Port</option><option value="saveconfig">Save Config</option>
        </select>
        <input id="cd1-port" type="number" min="${PORT_START}" max="${PORT_END}" value="${PORT_START}" style="background:#1a1a24;color:#fff;border:1px solid #27272a;border-radius:8px;padding:0.45rem;font-size:0.8rem;width:75px;"/>
        <select id="cd1-role" style="background:#1a1a24;color:#fff;border:1px solid #27272a;border-radius:8px;padding:0.45rem;font-size:0.8rem;">
            <option value="guest">Guest</option><option value="user">User</option><option value="admin">Admin</option>
        </select>
        <button onclick="cd1Send()" style="background:var(--accent);color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;">Send</button>
        <button onclick="cd1Ok()" style="background:var(--accent);color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;">OK</button>
    </div>
    <textarea id="cd1-textarea" placeholder="Connection idle..." style="width:100%;min-height:140px;background:#fff;color:#111;border:1px solid #27272a;border-radius:8px;padding:0.75rem;font-family:monospace;font-size:0.8rem;resize:vertical;"></textarea>
</div>

<% if (authorized) { %>
<section class="section">
    <div class="section-inner">
        <h2>Modules</h2>
        <div class="table-wrap"><table><thead><tr><th>Page</th><th>Port</th><th>Description</th></tr></thead><tbody>
$(for i in "${!PAGES[@]}"; do echo "            <tr><td><a href=\"${PAGE_FILES[$i]}.jsp\" style=\"color:var(--accent)\">${PAGES[$i]}</a></td><td>${PAGE_PORTS[$i]:-—}</td><td>${MODULE_NAME} ${PAGES[$i],,} module</td></tr>"; done)
        </tbody></table></div>
    </div>
</section>
<% } else { %>
<section class="section"><div class="section-inner" style="color:#fecaca;">Authorization Revoked — public.key not found.</div></section>
<% } %>

<script src="js/connector.js"></script>
</body>
</html>
INDEXEOF

# ============================================================================
# GENERATE: SQL schema from nouns
# ============================================================================
echo "[5] Generating SQL schema from nouns..."

cat > "$WEBAPP_DIR/sql/create-tables.sql" << SQLHEADER
-- ${MODULE_NAME}™ — Auto-generated schema
-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
CREATE DATABASE IF NOT EXISTS ${MODULE_DB};
USE ${MODULE_DB};

SQLHEADER

for i in "${!NOUNS[@]}"; do
    TABLE="${NOUN_TABLES[$i]}"
    IFS=',' read -ra COLS <<< "${NOUN_COLUMNS[$i]}"
    echo "CREATE TABLE IF NOT EXISTS ${TABLE} (" >> "$WEBAPP_DIR/sql/create-tables.sql"
    for col in "${COLS[@]}"; do
        col=$(echo "$col" | tr -d ' ')
        if [ "$col" = "id" ]; then
            echo "    id BIGINT AUTO_INCREMENT PRIMARY KEY," >> "$WEBAPP_DIR/sql/create-tables.sql"
        elif [[ "$col" == *"_at" ]]; then
            echo "    ${col} DATETIME DEFAULT CURRENT_TIMESTAMP," >> "$WEBAPP_DIR/sql/create-tables.sql"
        elif [[ "$col" == *"active"* ]] || [[ "$col" == *"enabled"* ]]; then
            echo "    ${col} BOOLEAN DEFAULT TRUE," >> "$WEBAPP_DIR/sql/create-tables.sql"
        elif [[ "$col" == *"count"* ]] || [[ "$col" == *"number"* ]] || [[ "$col" == *"year"* ]] || [[ "$col" == *"port"* ]]; then
            echo "    ${col} INT DEFAULT 0," >> "$WEBAPP_DIR/sql/create-tables.sql"
        else
            echo "    ${col} VARCHAR(255)," >> "$WEBAPP_DIR/sql/create-tables.sql"
        fi
    done
    # Remove trailing comma from last column
    sed -i '$ s/,$//' "$WEBAPP_DIR/sql/create-tables.sql"
    echo ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;" >> "$WEBAPP_DIR/sql/create-tables.sql"
    echo "" >> "$WEBAPP_DIR/sql/create-tables.sql"
done

# ============================================================================
# GENERATE: db.properties template
# ============================================================================
echo "[6] Generating db.properties..."

cat > "$WEBAPP_DIR/WEB-INF/db.properties" << DBEOF
# ${MODULE_NAME}™ — Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/${MODULE_DB}
db.user=root
db.password=
DBEOF

# ============================================================================
# GENERATE: web.xml
# ============================================================================
cat > "$WEBAPP_DIR/WEB-INF/web.xml" << WEBEOF
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee" version="6.0">
    <display-name>${MODULE_NAME}</display-name>
    <welcome-file-list><welcome-file>index.jsp</welcome-file></welcome-file-list>
    <session-config><session-timeout>30</session-timeout></session-config>
</web-app>
WEBEOF

# ============================================================================
# GENERATE: deploy-local.sh
# ============================================================================
echo "[7] Generating deploy script..."

cat > "$INSTALL_DIR/deploy-local.sh" << 'DEPLOYEOF'
#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOD_ROOT="$(dirname "$SCRIPT_DIR")"
WEBAPP_SRC="$MOD_ROOT/servlets/servlet/src/main/webapp"
TOMCAT_HOME="${CATALINA_HOME:-/opt/apache-tomcat-11.0.2}"
DEPLOYEOF

cat >> "$INSTALL_DIR/deploy-local.sh" << DEPLOYEOF2
CONTEXT="${MODULE_NAME,,}"
DEPLOY_DIR="\$TOMCAT_HOME/webapps/\$CONTEXT"

echo "[*] Deploying \$CONTEXT to \$DEPLOY_DIR..."
rm -rf "\$DEPLOY_DIR"
mkdir -p "\$DEPLOY_DIR/WEB-INF/lib"
cp -r "\$WEBAPP_SRC/"* "\$DEPLOY_DIR/"
chown -R tomcat:tomcat "\$DEPLOY_DIR" 2>/dev/null || true
echo "[✓] Deployed: http://localhost:8080/\$CONTEXT/"
DEPLOYEOF2

chmod +x "$INSTALL_DIR/deploy-local.sh"

# ============================================================================
# GENERATE: Smartphone mobile.css (copy from BMA)
# ============================================================================
echo "[8] Generating smartphone edition..."

cp "$PROJECT_ROOT/modules/black/presidential/Brarner.M.Alete/smartphone/css/mobile.css" "$SMART_DIR/css/mobile.css" 2>/dev/null || echo "    (BMA smartphone CSS not found — create manually)"
cp "$PROJECT_ROOT/modules/black/presidential/Brarner.M.Alete/smartphone/js/mobile.js" "$SMART_DIR/js/mobile.js" 2>/dev/null || echo "    (BMA smartphone JS not found — create manually)"

# ============================================================================
# DONE
# ============================================================================
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " [✓] Website generated: $OUT_DIR"
echo ""
echo " Files:"
find "$OUT_DIR" -type f | sed "s|$OUT_DIR|    .|" | sort
echo ""
echo " Next steps:"
echo "   1. Edit db.properties with MySQL credentials"
echo "   2. Run: mysql < $WEBAPP_DIR/sql/create-tables.sql"
echo "   3. Deploy: sudo bash $INSTALL_DIR/deploy-local.sh"
echo "   4. Access: http://localhost:8080/${MODULE_NAME,,}/"
echo "═══════════════════════════════════════════════════════════════"
