#!/usr/bin/env bash
# generate-structure.sh — Scans codebase and regenerates STRUCTURE.txt
# Called by ANT 'structure' target on compile or module addition.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/STRUCTURE.txt"
DATE=$(date +%Y-%m-%d)

cat > "$OUT" <<'HEADER'
JAVA NATIONAL FINANCE ENGINE — STRUCTURE
=========================================
HEADER

cat >> "$OUT" <<EOF
Version:        2911.15.0
Date:           $DATE
Owner:          Maximilian Eric Alexander Rupplin von Keffikon — MEARVK LLC
Contact:        https://github.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/discussions
Phone:          1.919.923.4239 (USA)
Languages:      American, English, French, Spanish, Thai, Italian, German, Japanese, Chinese, Arabic, Russian, Ukrainian, Turkish
Headquarters:   555 South Mangum St, Durham, NC 27701
Purpose:        IQ Conservatorship and Systems Design PhD+ of NCSU Math and Science and Harvard Law Final
Sorceress:      Elisabeth R. Harkins of Stanford Math and Yale Sciences (https://github.com/ElisabethHarkins5509)
Students:       Available on the 8th Floor after 8

Generated:      $DATE (auto-generated by scripts/generate-structure.sh)


SOURCE PACKAGES  (source/)
---------------------------
EOF

# Scan source packages
find "$ROOT/source" -name "*.java" | sort | while read f; do
    rel="${f#$ROOT/source/}"
    dir=$(dirname "$rel")
    class=$(basename "$f" .java)
    # Extract first line of class javadoc or class declaration
    desc=$(grep -m1 -oP '(?<=\* )[A-Z].*' "$f" 2>/dev/null | head -1)
    [ -z "$desc" ] && desc=$(grep -m1 "public.*class\|public.*interface" "$f" 2>/dev/null | sed 's/.*class //;s/.*interface //;s/ .*//')
    printf "  %-45s — %s\n" "$dir/$class" "${desc:0:80}" >> "$OUT"
done

cat >> "$OUT" <<EOF


MODULES  (modules/)
--------------------
EOF

# Scan module directories
for moddir in "$ROOT"/modules/*/; do
    [ -d "$moddir" ] || continue
    modname=$(basename "$moddir")
    jcount=$(find "$moddir" -name "*.java" 2>/dev/null | wc -l)
    xmlcount=$(find "$moddir" -name "*.xml" 2>/dev/null | wc -l)
    printf "  %-30s — %d Java files, %d XML configs\n" "$modname" "$jcount" "$xmlcount" >> "$OUT"

    # List Java files
    find "$moddir" -name "*.java" | sort | while read f; do
        rel="${f#$ROOT/modules/}"
        class=$(basename "$f" .java)
        printf "    %-40s\n" "$rel" >> "$OUT"
    done
done

cat >> "$OUT" <<EOF


CONFIGURATION  (configuration/)
--------------------------------
EOF

find "$ROOT/configuration" -name "*.xml" | sort | while read f; do
    rel=$(basename "$f")
    printf "  %s\n" "$rel" >> "$OUT"
done

cat >> "$OUT" <<EOF


LEARNING STRIPS  (source/*/strips/)
-------------------------------------
EOF

find "$ROOT/source" -path "*/strips/*.tsv" | sort | while read f; do
    rel="${f#$ROOT/}"
    printf "  %s\n" "$rel" >> "$OUT"
done

cat >> "$OUT" <<EOF


SCRIPTS  (scripts/)
--------------------
EOF

find "$ROOT/scripts" -name "*.sh" | sort | while read f; do
    rel="${f#$ROOT/scripts/}"
    printf "  %s\n" "$rel" >> "$OUT"
done

cat >> "$OUT" <<EOF


DATABASES
----------
  nwe                    — Main NWE database (NationalID, knowledge, trades)
  nwe_strernary          — Strernary knowledge_base, training_pairs
  nwe_japan              — Japan Signal Server
  nwe_russia             — Russia Signal Server
  nwe_mexico             — Mexico Signal Server
  nwe_greece_intl        — Greece International Signal Server
  nwe_gray_registry      — Gray Port Registry (leases, connections, payments, blocks)
  nwe_gray85_registry    — Gray.85 Crème Port Registry (leases, creme_unlocks, payments)


PORTS
------
EOF

# Extract ports from source
grep -rn "PORT\s*=" "$ROOT/source" --include="*.java" | grep -i "final\|static" | \
    grep -oP '\d{4,5}' | sort -un | while read p; do
    printf "  %s\n" "$p" >> "$OUT"
done

echo "" >> "$OUT"
echo "--- END STRUCTURE ---" >> "$OUT"
echo "[structure] Generated $OUT ($DATE)"
