# This config file is for Apache version 2.2.x and is installed
# into /etc/apache2/conf.d.  It is ignored by Apache version 2.4.x;
# that has its own configuration file available in
# /etc/apache2/conf-available
<Location ~ /cgi-bin/d(search|help_fetcher)(\?.*)?>
  order deny,allow
  deny from all
  allow from localhost
  Options -Indexes -MultiViews
</Location>

<Directory /usr/share/doc>
  order deny,allow
  deny from all
  allow from localhost
  Options Indexes MultiViews FollowSymLinks
</Directory>

# The following directives are needed for the operation of Debian Online Help
# and are assumed to already be enabled on the server's configuration:
#
#Alias /doc /usr/share/doc
#
#ScriptAlias /cgi-bin /usr/lib/cgi-bin
#<Directory /usr/lib/cgi-bin>
#  AllowOverride None
#  Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
#  order allow,deny
#  allow from all
#</Directory>
#
# Note that enabling /doc/ alias may result in a security vulnerability,
# specifically CVE-2012-0216. Thus newer versions of the apache2 package
# do NOT have the /doc/ alias enabled by default. 
#
# See http://www.debian.org/security/2012/dsa-2452 for reference and to
# decide whether the conditions stated there apply to your case.
#
# Then, enable the /doc/ alias by uncommenting the line above, if you judge
# that it is secure to do so. Else you can uncomment the following two lines
# to allow a secure partial operation of Debian Online Help, even if the
# above vulnerability is present:
#
#Alias /doc/HTML /usr/share/doc/HTML
#Alias /doc/dhelp/css /usr/share/doc/dhelp/css
#
# Using the above two alias you will be able to see descriptions and search
# for terms, but the documents themselves will be inaccessible. You will need
# to manually add an alias directive *for each document* that you want it to
# become accessible.
#
# See also /usr/share/doc/dhelp/README.Debian for more information.

