## dhelp-enable configuration snippet; enabled by dhelp postinst.
## Note that the # in the dependency line, below, is _required_.

# -*- depends: cgi, debian-doc -*-

## The stated dependencies above provide all dhelp needs. If however
## you want to create a custom configuration, the dhelp requirements
## are given below, commented out:
#
#server.modules += ( "mod_cgi" )
#
#$HTTP["url"] =~ "^/cgi-bin/" {
#        cgi.assign = ( "" => "" )
#}
#
## by default allow access only from localhost
#$HTTP["remoteip"] =~ "^127\.0\.0\.1$|^::1$" {
#        alias.url += (
#        "/cgi-bin/" => "/usr/lib/cgi-bin/",
#        "/doc/" => "/usr/share/doc/",
#        )
#        $HTTP["url"] =~ "^/doc/" {
#                dir-listing.activate = "enable"
#        }
#        $HTTP["url"] =~ "^/cgi-bin/" {
#                cgi.assign = ( "" => "" )
#        }
#}
#
## If you do not want to enable full access to /usr/share/doc, then
## replace the "/doc/" => ... line, with these:
#
#        "/doc/HTML/" => "/usr/share/doc/HTML/",
#        "/doc/dhelp/css/" => "/usr/share/doc/dhelp/css/",
#
## You will then need one more alias line *for each* document linked
## by dhelp's document index pages, else the links will return error.
##
## See /usr/share/doc/dhelp/README.debian for more information.

