## The default configuration file shipped by the mathopd debian package
## makes dhelp usable out-of-the-box. So there is no need to change
## anything.

## If however you want to create a custom configuration, the dhelp
## requirements are given below, commented out.

## The following fragment should be inserted inside the `Server{Virtual{...}}'
## block of the locally accessible virtual host:
#
#		Control {
#			Alias /doc
#			Location /usr/share/doc
#			Access {
#				Deny 0/0
#				Allow 127.0.0.1/32
#			}
#		}
#
## If you do not want to enable full access to /usr/share/doc, then
## replace the "... Alias /doc ..." control block, with these:
#
#		Control {
#			Alias /doc/dhelp/css
#			Location /usr/share/doc/dhelp/css
#			Access {
#				Deny 0/0
#				Allow 127.0.0.1/32
#			}
#		}
#		Control {
#			Alias /doc/HTML
#			Location /usr/share/doc/HTML
#			Access {
#				Deny 0/0
#				Allow 127.0.0.1/32
#			}
#		}
#
## You will then need one more alias control block *for each* document linked
## by dhelp's document index pages, else the links will return error.
##
## See /usr/share/doc/dhelp/README.debian for more information.

