## The default configuration file shipped by the nginx* debian packages
## makes dhelp usable for brwosing but with non-working CGI scripts,
## because nginx supports only FastCGI. 
##
## To enable CGI scripts on nginx, you have to install the fcgiwrap package
## and copy this line inside the `server {...}' block of the default virtual
## site at /etc/nginx/sites-available/default:
#
#	include /usr/share/doc/fcgiwrap/examples/nginx.conf
#
## Apart from the above, there is no need to change anything else.

## If however you want to create a custom configuration, the dhelp
## requirements are given below, commented out.

## The following fragment should be inserted inside the `server{ ... }'
## block of the locally accessible virtual host:
#
#	location /doc/ {
#		alias /usr/share/doc/;
#		autoindex on;
#		allow 127.0.0.1;
#		deny all;
#	}
#
## If you do not want to enable full access to /usr/share/doc, then
## replace the "location /doc ..." control block, with these:
#
#	location /doc/HTML {
#		alias /usr/share/doc/HTML;
#		autoindex on;
#		allow 127.0.0.1;
#		deny all;
#	}
#
#	location /doc/dhelp/css {
#		alias /usr/share/doc/dhelp/css;
#		allow 127.0.0.1;
#		deny all;
#	}
#
## You will then need one more location control block *for each* document
## linked by dhelp's document index pages, else the links will return error.
##
## See /usr/share/doc/dhelp/README.debian for more information.

