# German
header=Nationale Finanz-Engine  v2811.1
label.remote_ip=Remote-IP:
label.geo=Geografischer Standort:
label.time=Lokale Serverzeit:
label.uptime=Laufzeit:
label.memory=Gesamtspeicher:
label.connections=Aktuelle Verbindungen:
label.lang_menu=Sprachauswahl:
label.lang_prompt=Eingabe: lang <Code>  (ja cn ru th es fr de it en)
label.lang_revert=Zurueck zu Englisch: lang en
