# Spanish
header=Motor Financiero Nacional  v2811.1
label.remote_ip=IP Remota:
label.geo=Ubicacion Geografica:
label.time=Hora Local del Servidor:
label.uptime=Tiempo Activo:
label.memory=Memoria Total:
label.connections=Conexiones Actuales:
label.lang_menu=Seleccion de Idioma:
label.lang_prompt=Escriba: lang <codigo>  (ja cn ru th es fr de it en)
label.lang_revert=Volver al ingles: lang en
