# French
header=Moteur Financier National  v2811.1
label.remote_ip=IP Distante:
label.geo=Localisation Geo:
label.time=Heure Locale du Serveur:
label.uptime=Temps de Fonctionnement:
label.memory=Memoire Totale:
label.connections=Connexions Actuelles:
label.lang_menu=Choix de la Langue:
label.lang_prompt=Tapez: lang <code>  (ja cn ru th es fr de it en)
label.lang_revert=Revenir a l'anglais: lang en
