# Italian
header=Motore Finanziario Nazionale  v2811.1
label.remote_ip=IP Remoto:
label.geo=Posizione Geografica:
label.time=Ora Locale del Server:
label.uptime=Tempo di Attivita:
label.memory=Memoria Totale:
label.connections=Connessioni Correnti:
label.lang_menu=Selezione Lingua:
label.lang_prompt=Digitare: lang <codice>  (ja cn ru th es fr de it en)
label.lang_revert=Torna all'inglese: lang en
