---
abstract: 'programmable DNS resolver class for offline emulation of DNS'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-DNS-Resolver-Programmable
no_index:
  directory:
    - t
    - inc
requires:
  Net::DNS: '0.69'
  perl: '5.006'
resources:
  bugtracker: https://github.com/bigpresh/Net-DNS-Resolver-Programmable/issues
  homepage: https://github.com/bigpresh/Net-DNS-Resolver-Programmable
  repository: https://github.com/bigpresh/Net-DNS-Resolver-Programmable
version: '0.009'
