#!/usr/bin/env bash
# Ubuntu White Edition Chromium build wrapper.
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
CHROMIUM_SRC=${CHROMIUM_SRC:-"$SCRIPT_DIR/../chromium-src"}
CHROMIUM_OUT=${CHROMIUM_OUT:-"$CHROMIUM_SRC/out/WhiteEdition"}
MODE=${1:-check}

fail() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

check_source() {
    [ -d "$CHROMIUM_SRC" ] || fail "Chromium source directory missing: $CHROMIUM_SRC"
    [ -f "$CHROMIUM_SRC/DEPS" ] || fail "not a Chromium checkout: DEPS missing"
    [ -d "$CHROMIUM_SRC/chrome" ] || fail "unusual source structure: chrome/ missing"
    [ -d "$CHROMIUM_SRC/content" ] || fail "unusual source structure: content/ missing"
    [ -d "$CHROMIUM_SRC/components" ] || fail "unusual source structure: components/ missing"
    [ -f "$CHROMIUM_SRC/BUILD.gn" ] || fail "unusual source structure: BUILD.gn missing"
}

write_args() {
    mkdir -p "$CHROMIUM_OUT"
    printf '%s\n' \
        '# Ubuntu White Edition Chromium development build.' \
        '# Generated by build-white-edition.sh.' \
        'is_debug = true' \
        'symbol_level = 1' \
        'blink_symbol_level = 0' \
        'v8_symbol_level = 0' \
        'is_official_build = false' \
        'is_chrome_branded = false' \
        > "$CHROMIUM_OUT/args.gn"
    if [ -n "${TARGET_CPU:-}" ]; then
        printf 'target_cpu = "%s"\n' "$TARGET_CPU" >> "$CHROMIUM_OUT/args.gn"
    fi
}

case "$MODE" in
    check)
        need_cmd gn
        check_source
        printf 'Chromium source: %s\n' "$CHROMIUM_SRC"
        printf 'GN output:       %s\n' "$CHROMIUM_OUT"
        printf 'Source layout:   OK\n'
        ;;
    gen)
        need_cmd gn
        check_source
        write_args
        (cd "$CHROMIUM_SRC" && gn gen "$CHROMIUM_OUT")
        (cd "$CHROMIUM_SRC" && gn check "$CHROMIUM_OUT")
        ;;
    build)
        need_cmd gn
        need_cmd autoninja
        check_source
        write_args
        (cd "$CHROMIUM_SRC" && gn gen "$CHROMIUM_OUT")
        if [ -n "${BUILD_JOBS:-}" ]; then
            (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" -j "$BUILD_JOBS" chrome)
        else
            (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" chrome)
        fi
        ;;
    test)
        need_cmd autoninja
        check_source
        [ -d "$CHROMIUM_OUT" ] || fail "build directory missing; run gen first"
        (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" unit_tests)
        ;;
    *)
        printf 'Usage: %s {check|gen|build|test}\n' "$0" >&2
        exit 2
        ;;
esac
