#!/usr/bin/env bash
# Ubuntu White Edition Chromium build wrapper.
# Performs source/dependency preflight before invoking GN or Ninja.
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
CHROMIUM_SRC=${CHROMIUM_SRC:-"$SCRIPT_DIR/../chromium-src"}
CHROMIUM_OUT=${CHROMIUM_OUT:-"$CHROMIUM_SRC/out/WhiteEdition"}
DEPOT_TOOLS=${DEPOT_TOOLS:-"$SCRIPT_DIR/../depot_tools"}
MODE=${1:-check}

fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

setup_tools() {
    [ -d "$DEPOT_TOOLS" ] || return 0
    case ":$PATH:" in
        *":$DEPOT_TOOLS:"*) ;;
        *) PATH="$DEPOT_TOOLS:$PATH"; export PATH ;;
    esac
}

find_gn() {
    if command -v gn >/dev/null 2>&1; then GN_BIN=$(command -v gn); return; fi
    [ -x "$CHROMIUM_SRC/buildtools/linux64/gn" ] && { GN_BIN="$CHROMIUM_SRC/buildtools/linux64/gn"; return; }
    fail "GN not found. Run userland/chromium/install-gn.sh first."
}

need_autoninja() {
    command -v autoninja >/dev/null 2>&1 || fail "autoninja not found. Run userland/chromium/install-gn.sh first."
}

check_source() {
    [ -d "$CHROMIUM_SRC" ] || fail "Chromium source directory missing: $CHROMIUM_SRC"
    [ -f "$CHROMIUM_SRC/DEPS" ] || fail "not a Chromium checkout: DEPS missing"
    [ -f "$CHROMIUM_SRC/BUILD.gn" ] || fail "unusual source structure: BUILD.gn missing"
    for d in chrome content components third_party; do
        [ -d "$CHROMIUM_SRC/$d" ] || fail "unusual source structure: $d/ missing"
    done
}

check_required_files() {
    # These are known GN imports required by the Chromium tree. Add entries
    # here when GN reports a missing dependency rather than creating stubs.
    local required=(
        "third_party/angle/dotfile_settings.gni"
    )
    local missing=0 file
    for file in "${required[@]}"; do
        if [ ! -f "$CHROMIUM_SRC/$file" ]; then
            printf 'MISSING DEPENDENCY: %s\n' "$file" >&2
            missing=1
        fi
    done
    if [ "$missing" -ne 0 ]; then
        printf '%s\n' "Chromium dependency tree is incomplete." >&2
        printf '%s\n' "Repair with: gclient sync && gclient runhooks" >&2
        printf '%s\n' "Do not create placeholder .gni files." >&2
        exit 1
    fi
}

check_source_tree() {
    check_source
    check_required_files
}

write_args() {
    mkdir -p "$CHROMIUM_OUT"
    printf '%s\n' \
        '# Ubuntu White Edition Chromium development build.' \
        '# Generated by build-white-edition.sh.' \
        'is_debug = true' \
        'symbol_level = 1' \
        'blink_symbol_level = 0' \
        'v8_symbol_level = 0' \
        'is_official_build = false' \
        'is_chrome_branded = false' \
        > "$CHROMIUM_OUT/args.gn"
    if [ -n "${TARGET_CPU:-}" ]; then
        printf 'target_cpu = "%s"\n' "$TARGET_CPU" >> "$CHROMIUM_OUT/args.gn"
    fi
}

setup_tools

case "$MODE" in
    check)
        find_gn
        check_source_tree
        printf 'Chromium source: %s\n' "$CHROMIUM_SRC"
        printf 'GN output:       %s\n' "$CHROMIUM_OUT"
        printf 'GN:              %s\n' "$GN_BIN"
        printf 'Source/deps:     OK\n'
        ;;
    gen)
        find_gn
        check_source_tree
        write_args
        (cd "$CHROMIUM_SRC" && "$GN_BIN" gen "$CHROMIUM_OUT")
        (cd "$CHROMIUM_SRC" && "$GN_BIN" check "$CHROMIUM_OUT")
        ;;
    build)
        find_gn
        need_autoninja
        check_source_tree
        write_args
        (cd "$CHROMIUM_SRC" && "$GN_BIN" gen "$CHROMIUM_OUT")
        if [ -n "${BUILD_JOBS:-}" ]; then
            (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" -j "$BUILD_JOBS" chrome)
        else
            (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" chrome)
        fi
        ;;
    test)
        need_autoninja
        check_source_tree
        [ -d "$CHROMIUM_OUT" ] || fail "build directory missing; run gen first"
        (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" unit_tests)
        ;;
    *)
        printf 'Usage: %s {check|gen|build|test}\n' "$0" >&2
        exit 2
        ;;
esac
