#!/usr/bin/env bash
# Ubuntu White Edition Chromium build preflight/build wrapper.
#
# This script intentionally keeps Chromium's upstream source tree separate from
# project configuration and generated output. It checks the expected source
# layout, writes a reproducible GN args file, generates the build directory,
# validates GN targets, and optionally builds chrome.
#
# Usage:
#   ./build-white-edition.sh check
#   ./build-white-edition.sh gen
#   ./build-white-edition.sh build
#   ./build-white-edition.sh test
#
# Environment overrides:
#   CHROMIUM_SRC   Chromium checkout (default: ../chromium-src relative to this dir)
#   CHROMIUM_OUT   GN output directory (default: <source>/out/WhiteEdition)
#   TARGET_CPU     target CPU override, if needed
#   BUILD_JOBS     passed to autoninja as -jN

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CHROMIUM_SRC="${CHROMIUM_SRC:-${SCRIPT_DIR}/../chromium-src}"
CHROMIUM_OUT="${CHROMIUM_OUT:-${CHROMIUM_SRC}/out/WhiteEdition}"
MODE="${1:-check}"

fail() { echo "ERROR: $*" >&2; exit 1; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"; }

check_source() {
  [[ -d "$CHROMIUM_SRC" ]] || fail "Chromium source directory missing: $CHROMIUM_SRC"
  [[ -f "$CHROMIUM_SRC/DEPS" ]] || fail "not a Chromium checkout: missing DEPS"
  [[ -d "$CHROMIUM_SRC/chrome" ]] || fail "unusual source structure: chrome/ missing"
  [[ -d "$CHROMIUM_SRC/content" ]] || fail "unusual source structure: content/ missing"
  [[ -d "$CHROMIUM_SRC/components" ]] || fail "unusual source structure: components/ missing"
  [[ -f "$CHROMIUM_SRC/BUILD.gn" ]] || fail "unusual source structure: top-level BUILD.gn missing"
  [[ -f "$CHROMIUM_SRC/args.gn" ]] && fail "unexpected source-root args.gn; use out/WhiteEdition/args.gn instead"
}

write_args() {
  mkdir -p "$CHROMIUM_OUT"
  cat > "$CHROMIUM_OUT/args.gn" <<EOF
# Ubuntu White Edition Chromium development build.
# Generated by userland/chromium/http-3.0/build-white-edition.sh.
# Do not put generated output in the Chromium source tree.

is_debug = true
symbol_level = 1
blink_symbol_level = 0
v8_symbol_level = 0

# Keep the build suitable for local development/testing.
is_official_build = false
is_chrome_branded = false

# White Edition feature contract; consumed only after corresponding source
# integration exists. These names must be declared by the patched source tree.
# white_edition_ui = true
# white_edition_http_io = true
# white_edition_secondary_taskbar = true
# white_edition_http_io_width_ratio = 0.80

EOF
  if [[ -n "${TARGET_CPU:-}" ]]; then
    printf 'target_cpu = "%s"\n' "$TARGET_CPU" >> "$CHROMIUM_OUT/args.gn"
  fi
}

check) 
  need_cmd gn
  check_source
  echo "Chromium source: $CHROMIUM_SRC"
  echo "GN output:       $CHROMIUM_OUT"
  echo "Source layout:   OK"
  echo "Build values:    args.gn will use debug + reduced symbols + unbranded Chromium"
  ;;
gen)
  need_cmd gn
  check_source
  write_args
  (cd "$CHROMIUM_SRC" && gn gen "$CHROMIUM_OUT")
  (cd "$CHROMIUM_SRC" && gn check "$CHROMIUM_OUT")
  ;;
build)
  need_cmd gn
  need_cmd autoninja
  check_source
  write_args
  (cd "$CHROMIUM_SRC" && gn gen "$CHROMIUM_OUT")
  if [[ -n "${BUILD_JOBS:-}" ]]; then
    (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" -j"$BUILD_JOBS" chrome)
  else
    (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" chrome)
  fi
  ;;
test)
  need_cmd autoninja
  check_source
  [[ -d "$CHROMIUM_OUT" ]] || fail "build directory does not exist; run gen or build first"
  (cd "$CHROMIUM_SRC" && autoninja -C "$CHROMIUM_OUT" unit_tests)
  ;;
*)
  echo "Usage: $0 {check|gen|build|test}" >&2
  exit 2
  ;;
esac
