/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.2
 * Generated at: 2026-06-29 01:11:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.*;
import java.io.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // Check GitHub repo authorization (public.key presence)
    String ghKeyUrl = "https://raw.githubusercontent.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/main/psychiatry/secrets/public.key";
    boolean authorized = false;
    String authStatus = "Unknown";
    try {
        HttpURLConnection hc = (HttpURLConnection) new URL(ghKeyUrl).openConnection();
        hc.setRequestMethod("HEAD");
        hc.setConnectTimeout(5000);
        hc.setReadTimeout(5000);
        int code = hc.getResponseCode();
        hc.disconnect();
        authorized = (code == 200);
        authStatus = authorized ? "Authorized (public.key present)" : "Revoked (HTTP " + code + ")";
    } catch (Exception e) {
        authStatus = "Check failed: " + (e.getMessage() != null ? e.getMessage() : "timeout");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\"/>\n");
      out.write("    <title>Brarner.M.Alete™ — Presidential Species/Postal/SSA/Art/Science Module</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"nav\"><div class=\"nav-inner\">\n");
      out.write("    <a href=\"index.jsp\" class=\"nav-brand\"><img src=\"images/mearvk.ltd.logo.left.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-right:8px;background:transparent;\"/>Brarner.M.Alete™<img src=\"images/mearvk.ltd.logo.right.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-left:8px;background:transparent;\"/></a>\n");
      out.write("    <ul class=\"nav-links\">\n");
      out.write("        <li><a href=\"index.jsp\" class=\"active\">Overview</a></li>\n");
      out.write("        <li><a href=\"species.jsp\">Species</a></li>\n");
      out.write("        <li><a href=\"postal.jsp\">Postal</a></li>\n");
      out.write("        <li><a href=\"art.jsp\">Art</a></li>\n");
      out.write("        <li><a href=\"science.jsp\">Science</a></li>\n");
      out.write("        <li><a href=\"status.jsp\">Status</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"nav-actions\">\n");
      out.write("        <a href=\"guest.jsp\" class=\"nav-cta\">Guest</a>\n");
      out.write("        <a href=\"register.jsp\" class=\"nav-cta\">Register</a>\n");
      out.write("        <a href=\"admin/login.xhtml\" class=\"nav-cta\">Admin →</a>\n");
      out.write("    </div>\n");
      out.write("</div></nav>\n");
      out.write("\n");
      out.write("<section class=\"hero\">\n");
      out.write("    <div class=\"hero-inner\">\n");
      out.write("        <span class=\"hero-tag\">NC Socialist-College Block</span>\n");
      out.write("        <h1>Brarner.M.Alete™</h1>\n");
      out.write("        <p>Presidential species, postal, SSA, art and science module. Maven multi-module architecture with servlets, EJB, and EAR packaging — maintained by MEARVK LLC.</p>\n");
      out.write("        <div class=\"hero-actions\">\n");
      out.write("            <a href=\"https://github.com/mearvk/Java.Web.Server.Telnet.Front.Java.21/releases/latest\" class=\"btn btn-primary\">Download Now</a>\n");
      out.write("            <a href=\"#roadmap\" class=\"btn btn-ghost\">View Roadmap →</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- CD1 Connector Button + Floating Dialog -->\n");
      out.write("<div style=\"display:flex;justify-content:center;align-items:center;width:100%;padding:2rem 0;\">\n");
      out.write("    <button id=\"cd1-btn\" type=\"button\" aria-pressed=\"false\" style=\"all:unset;display:block;margin:0 auto;cursor:pointer;padding:0;border:none;background:transparent;transition:transform 0.3s cubic-bezier(0.42,-1.84,0.42,1.84),filter 0.3s ease;\">\n");
      out.write("        <img src=\"images/black.button.png\" alt=\"Connector\" style=\"display:block;width:80px;height:80px;border-radius:50%;background:transparent;\"/>\n");
      out.write("    </button>\n");
      out.write("</div>\n");
      out.write("<div id=\"cd1-overlay\" style=\"display:none;position:fixed;inset:0;z-index:299;background:transparent;\"></div>\n");
      out.write("<div id=\"cd1-dialog\" style=\"display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:300;background:#111118;border:1px solid #27272a;border-radius:12px;padding:1.25rem;width:520px;max-width:90vw;box-shadow:0 8px 32px rgba(0,0,0,0.6);\">\n");
      out.write("    <div style=\"font-size:0.9rem;font-weight:600;color:#fff;margin-bottom:0.75rem;\">BMA Connector &#8212; Overview</div>\n");
      out.write("    <div style=\"display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;\">\n");
      out.write("        <select id=\"cd1-action\" style=\"background:#1a1a24;color:#fff;border:1px solid #27272a;border-radius:8px;padding:0.45rem 2rem 0.45rem 0.75rem;font-size:0.8rem;cursor:pointer;appearance:none;\">\n");
      out.write("            <option value=\"connect\">Connect</option>\n");
      out.write("            <option value=\"disconnect\">Disconnect</option>\n");
      out.write("            <option value=\"poll\">Poll Area Data</option>\n");
      out.write("            <option value=\"hardreset\">Hard Reset Connection</option>\n");
      out.write("        </select>\n");
      out.write("        <button onclick=\"cd1Send()\" style=\"background:#3b82f6;color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;\">Send</button>\n");
      out.write("        <button onclick=\"cd1Ok()\" style=\"background:#3b82f6;color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;\">OK</button>\n");
      out.write("    </div>\n");
      out.write("    <textarea id=\"cd1-textarea\" placeholder=\"Connection idle...\" spellcheck=\"false\" style=\"width:100%;min-height:140px;background:#ffffff;color:#111;border:1px solid #27272a;border-radius:8px;padding:0.75rem;font-family:monospace;font-size:0.8rem;resize:vertical;\"></textarea>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section\" id=\"roadmap\">\n");
      out.write("    <div class=\"section-inner\">\n");
      out.write("        <div style=\"margin-bottom:2rem;padding:1rem;border:1px solid ");
      out.print( authorized ? "#22c55e" : "#ef4444" );
      out.write(";border-radius:8px;background:");
      out.print( authorized ? "rgba(34,197,94,0.05)" : "rgba(239,68,68,0.05)" );
      out.write(";\">\n");
      out.write("            <span style=\"font-size:0.85rem;color:");
      out.print( authorized ? "#22c55e" : "#ef4444" );
      out.write(";font-weight:600;\">&#9679; ");
      out.print( authStatus );
      out.write("</span>\n");
      out.write("            <span style=\"font-size:0.75rem;color:#71717a;margin-left:1rem;\">Checked: ");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss z").format(new java.util.Date()) );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <h2>Roadmap</h2>\n");
      out.write("        <p>Module release schedule and versioning. All releases LTS.</p>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table>\n");
      out.write("                <thead><tr><th>Release</th><th>GA Date</th><th>Tag</th><th>Min JDK</th><th>LTS</th></tr></thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr><td><code>US.Congress.Edition</code></td><td>Jun 2026</td><td>Mearvk-US.Congress.Edition</td><td><code>21</code></td><td>yes</td></tr>\n");
      out.write("                    <tr><td><code>v9.9.1</code></td><td>May 2026</td><td>v9.9.1</td><td><code>21</code></td><td>yes</td></tr>\n");
      out.write("                    <tr><td><code>Mearvk-3.0</code></td><td>May 2026</td><td>Mearvk-3.0</td><td><code>21</code></td><td>yes</td></tr>\n");
      out.write("                    <tr><td><code>Mearvk-2.0</code></td><td>May 2026</td><td>Mearvk-2.0</td><td><code>21</code></td><td>yes</td></tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"section-inner\">\n");
      out.write("        <h2>Module Components</h2>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table>\n");
      out.write("                <thead><tr><th>Component</th><th>Description</th><th>Link</th></tr></thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr><td>Species</td><td>Biological classification — animalia, plantae, fungi, protista</td><td><a href=\"species.jsp\">Browse →</a></td></tr>\n");
      out.write("                    <tr><td>Postal</td><td>US Postal code lookup and validation for all 50 states</td><td><a href=\"postal.jsp\">Browse →</a></td></tr>\n");
      out.write("                    <tr><td>Art</td><td>Art museum collections indexer — 22 institutions</td><td><a href=\"art.jsp\">Browse →</a></td></tr>\n");
      out.write("                    <tr><td>Science</td><td>Scientific publication indexer with DOI resolution</td><td><a href=\"science.jsp\">Browse →</a></td></tr>\n");
      out.write("                    <tr><td>Status</td><td>Real-time module health monitoring</td><td><a href=\"status.jsp\">View →</a></td></tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\"><div class=\"footer-bottom\">\n");
      out.write("    <span>&#169; 2026 MEARVK LLC. All rights reserved.</span>\n");
      out.write("</div></footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function() {\n");
      out.write("    var btn = document.getElementById(\"cd1-btn\");\n");
      out.write("    var dialog = document.getElementById(\"cd1-dialog\");\n");
      out.write("    var overlay = document.getElementById(\"cd1-overlay\");\n");
      out.write("    var textarea = document.getElementById(\"cd1-textarea\");\n");
      out.write("    if (!btn || !dialog || !overlay || !textarea) return;\n");
      out.write("    btn.addEventListener(\"click\", function() {\n");
      out.write("        if (dialog.style.display !== \"none\") {\n");
      out.write("            dialog.style.display = \"none\";\n");
      out.write("            overlay.style.display = \"none\";\n");
      out.write("            btn.style.transform = \"\";\n");
      out.write("            btn.style.filter = \"\";\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        btn.style.transform = \"scale(0.9)\";\n");
      out.write("        btn.style.filter = \"drop-shadow(0 0 8px #3b82f6)\";\n");
      out.write("        setTimeout(function() {\n");
      out.write("            btn.style.transform = \"\";\n");
      out.write("            btn.style.filter = \"\";\n");
      out.write("            dialog.style.display = \"block\";\n");
      out.write("            overlay.style.display = \"block\";\n");
      out.write("        }, 750);\n");
      out.write("    });\n");
      out.write("    overlay.addEventListener(\"click\", function() { dialog.style.display = \"none\"; overlay.style.display = \"none\"; });\n");
      out.write("})();\n");
      out.write("function cd1Send() { var s = document.getElementById(\"cd1-action\"); var t = document.getElementById(\"cd1-textarea\"); if(!s||!t)return; t.value += \"[\" + new Date().toLocaleTimeString() + \"] \" + s.value + \" sent.\\n\"; }\n");
      out.write("function cd1Ok() { var t = document.getElementById(\"cd1-textarea\"); if(!t)return; t.value += \"[\" + new Date().toLocaleTimeString() + \"] OK.\\n\"; }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
