/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.2
 * Generated at: 2026-06-29 01:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.Properties;
import java.io.InputStream;

public final class species_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\"/>\n");
      out.write("    <title>Species — Brarner.M.Alete™</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"nav\"><div class=\"nav-inner\">\n");
      out.write("    <a href=\"index.jsp\" class=\"nav-brand\"><img src=\"images/mearvk.ltd.logo.left.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-right:8px;background:transparent;\"/>Brarner.M.Alete™<img src=\"images/mearvk.ltd.logo.right.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-left:8px;background:transparent;\"/></a>\n");
      out.write("    <ul class=\"nav-links\">\n");
      out.write("        <li><a href=\"index.jsp\">Overview</a></li>\n");
      out.write("        <li><a href=\"species.jsp\" class=\"active\">Species</a></li>\n");
      out.write("        <li><a href=\"postal.jsp\">Postal</a></li>\n");
      out.write("        <li><a href=\"art.jsp\">Art</a></li>\n");
      out.write("        <li><a href=\"science.jsp\">Science</a></li>\n");
      out.write("        <li><a href=\"status.jsp\">Status</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"nav-actions\">\n");
      out.write("        <a href=\"guest.jsp\" class=\"nav-cta\">Guest</a>\n");
      out.write("        <a href=\"register.jsp\" class=\"nav-cta\">Register</a>\n");
      out.write("        <a href=\"admin/login.xhtml\" class=\"nav-cta\">Admin →</a>\n");
      out.write("    </div>\n");
      out.write("</div></nav>\n");
      out.write("\n");
      out.write("<section class=\"hero\" style=\"padding:4rem 2rem;\">\n");
      out.write("    <div class=\"hero-inner\">\n");
      out.write("        <span class=\"hero-tag\">Biological Classification</span>\n");
      out.write("        <h1>Species Database</h1>\n");
      out.write("        <p>Comprehensive species classification with 12 sub-categories covering animalia, plantae, fungi, and protista kingdoms.</p>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- CD1 Connector Button + Floating Dialog -->\n");
      out.write("<div style=\"display:flex;justify-content:center;align-items:center;width:100%;padding:2rem 0;\">\n");
      out.write("    <button id=\"cd1-btn\" type=\"button\" aria-pressed=\"false\" style=\"all:unset;display:block;margin:0 auto;cursor:pointer;padding:0;border:none;background:transparent;transition:transform 0.3s cubic-bezier(0.42,-1.84,0.42,1.84),filter 0.3s ease;\">\n");
      out.write("        <img src=\"images/black.button.png\" alt=\"Connector\" style=\"display:block;width:80px;height:80px;border-radius:50%;background:transparent;\"/>\n");
      out.write("    </button>\n");
      out.write("</div>\n");
      out.write("<div id=\"cd1-overlay\" style=\"display:none;position:fixed;inset:0;z-index:299;background:transparent;\"></div>\n");
      out.write("<div id=\"cd1-dialog\" style=\"display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:300;background:#111118;border:1px solid #27272a;border-radius:12px;padding:1.25rem;width:520px;max-width:90vw;box-shadow:0 8px 32px rgba(0,0,0,0.6);\">\n");
      out.write("    <div style=\"font-size:0.9rem;font-weight:600;color:#fff;margin-bottom:0.75rem;\">BMA Connector &#8212; Species Division</div>\n");
      out.write("    <div style=\"display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;\">\n");
      out.write("        <select id=\"cd1-action\" style=\"background:#1a1a24;color:#fff;border:1px solid #27272a;border-radius:8px;padding:0.45rem 2rem 0.45rem 0.75rem;font-size:0.8rem;cursor:pointer;appearance:none;\">\n");
      out.write("            <option value=\"connect\">Connect</option>\n");
      out.write("            <option value=\"disconnect\">Disconnect</option>\n");
      out.write("            <option value=\"poll\">Poll Area Data</option>\n");
      out.write("            <option value=\"hardreset\">Hard Reset Connection</option>\n");
      out.write("        </select>\n");
      out.write("        <button onclick=\"cd1Send()\" style=\"background:#3b82f6;color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;\">Send</button>\n");
      out.write("        <button onclick=\"cd1Ok()\" style=\"background:#3b82f6;color:#fff;border:none;border-radius:8px;padding:0.45rem 1rem;font-size:0.8rem;font-weight:600;cursor:pointer;\">OK</button>\n");
      out.write("    </div>\n");
      out.write("    <textarea id=\"cd1-textarea\" placeholder=\"Connection idle...\" spellcheck=\"false\" style=\"width:100%;min-height:140px;background:#ffffff;color:#111;border:1px solid #27272a;border-radius:8px;padding:0.75rem;font-family:monospace;font-size:0.8rem;resize:vertical;\"></textarea>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"section-inner\">\n");
      out.write("        <h2>Browse by Kingdom</h2>\n");

    String kingdom = request.getParameter("kingdom");
    if (kingdom == null || kingdom.isEmpty()) kingdom = "Animalia";

    Connection conn = null;
    Properties dbProps = new Properties();
    boolean propsLoaded = false;
    try {
        InputStream dbIn = application.getResourceAsStream("/WEB-INF/db.properties");
        if (dbIn != null) { dbProps.load(dbIn); dbIn.close(); propsLoaded = true; }
        if (!propsLoaded) {
            String rp = application.getRealPath("/WEB-INF/db.properties");
            if (rp != null && new java.io.File(rp).exists()) {
                java.io.FileInputStream fis = new java.io.FileInputStream(rp);
                dbProps.load(fis); fis.close(); propsLoaded = true;
            }
        }
        if (!propsLoaded) {
            String[] tryPaths = { "/opt/tomcat/webapps/brarner.m.alete/WEB-INF/db.properties",
                System.getProperty("user.dir") + "/servlets/servlet/src/main/webapp/WEB-INF/db.properties",
                "/mnt/blockstorage/Java.Web.Server.Telnet.Front.Java.21/modules/black/presidential/Brarner.M.Alete/servlets/servlet/src/main/webapp/WEB-INF/db.properties" };
            for (String tp : tryPaths) { java.io.File f = new java.io.File(tp);
                if (f.exists()) { java.io.FileInputStream fis = new java.io.FileInputStream(f); dbProps.load(fis); fis.close(); propsLoaded = true; break; } }
        }
        String dbUrl = dbProps.getProperty("db.url", "jdbc:mysql://localhost:3306/BrarnerScience");
        String dbUser = dbProps.getProperty("db.user", "root");
        String dbPass = dbProps.getProperty("db.password", "");
        Class.forName(dbProps.getProperty("db.driver", "com.mysql.cj.jdbc.Driver"));
        conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

        // Classes for selected kingdom
        PreparedStatement psClass = conn.prepareStatement(
            "SELECT DISTINCT class_name, COUNT(DISTINCT order_name) AS orders, COUNT(DISTINCT family_name) AS families " +
            "FROM animalia WHERE kingdom=? AND class_name IS NOT NULL AND class_name!='' GROUP BY class_name ORDER BY class_name");
        psClass.setString(1, kingdom);
        ResultSet rsClass = psClass.executeQuery();

      out.write("\n");
      out.write("        <div class=\"tabs\">\n");
      out.write("            <a href=\"species.jsp?kingdom=Animalia\" class=\"tab ");
      out.print( "Animalia".equals(kingdom) ? "active" : "" );
      out.write("\">Animalia</a>\n");
      out.write("            <a href=\"species.jsp?kingdom=Plantae\" class=\"tab ");
      out.print( "Plantae".equals(kingdom) ? "active" : "" );
      out.write("\">Plantae</a>\n");
      out.write("            <a href=\"species.jsp?kingdom=Fungi\" class=\"tab ");
      out.print( "Fungi".equals(kingdom) ? "active" : "" );
      out.write("\">Fungi</a>\n");
      out.write("            <a href=\"species.jsp?kingdom=Protista\" class=\"tab ");
      out.print( "Protista".equals(kingdom) ? "active" : "" );
      out.write("\">Protista</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h3>");
      out.print( kingdom );
      out.write(" Classes</h3>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table>\n");
      out.write("                <thead><tr><th>Class</th><th>Orders</th><th>Families</th></tr></thead>\n");
      out.write("                <tbody>\n");

        String selClass = request.getParameter("class");
        boolean hasRows = false;
        while (rsClass.next()) {
            hasRows = true;
            String className = rsClass.getString("class_name");
            int orders = rsClass.getInt("orders");
            int families = rsClass.getInt("families");
            boolean isSelected = className != null && className.equals(selClass);

      out.write("\n");
      out.write("                    <tr style=\"");
      out.print( isSelected ? "background:rgba(59,130,246,0.08);border-left:3px solid #3b82f6;" : "" );
      out.write("\">\n");
      out.write("                        <td><a href=\"species.jsp?kingdom=");
      out.print( kingdom );
      out.print( isSelected ? "" : "&class=" + java.net.URLEncoder.encode(className, "UTF-8") );
      out.write("\" style=\"");
      out.print( isSelected ? "color:#3b82f6;font-weight:600;" : "" );
      out.write('"');
      out.write('>');
      out.print( className != null ? className : "(unnamed)" );
      out.print( isSelected ? " ▼" : "" );
      out.write("</a></td>\n");
      out.write("                        <td>");
      out.print( orders );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( families );
      out.write("</td>\n");
      out.write("                    </tr>\n");

            // Expand orders inline under the selected class
            if (isSelected) {
                PreparedStatement psOrder = conn.prepareStatement(
                    "SELECT DISTINCT order_name, COUNT(DISTINCT family_name) AS families " +
                    "FROM animalia WHERE class_name=? AND order_name IS NOT NULL AND order_name!='' GROUP BY order_name ORDER BY order_name");
                psOrder.setString(1, selClass);
                ResultSet rsOrder = psOrder.executeQuery();
                String selOrder = request.getParameter("order");

      out.write("\n");
      out.write("                    <tr><td colspan=\"3\" style=\"padding:0;\">\n");
      out.write("                        <div style=\"margin:0.5rem 1rem 1rem 1.5rem;\">\n");
      out.write("                            <strong style=\"font-size:0.85rem;color:#a1a1aa;\">Orders in ");
      out.print( selClass );
      out.write("</strong>\n");
      out.write("                            <table style=\"margin-top:0.5rem;width:100%;\">\n");
      out.write("                                <thead><tr><th>Order</th><th>Families</th></tr></thead>\n");
      out.write("                                <tbody>\n");

                boolean hasOrders = false;
                while (rsOrder.next()) {
                    hasOrders = true;
                    String orderName = rsOrder.getString("order_name");
                    int fam = rsOrder.getInt("families");
                    boolean orderSelected = orderName != null && orderName.equals(selOrder);

      out.write("\n");
      out.write("                                    <tr style=\"");
      out.print( orderSelected ? "background:rgba(59,130,246,0.06);" : "" );
      out.write("\">\n");
      out.write("                                        <td><a href=\"species.jsp?kingdom=");
      out.print( kingdom );
      out.write("&class=");
      out.print( java.net.URLEncoder.encode(selClass, "UTF-8") );
      out.print( orderSelected ? "" : "&order=" + java.net.URLEncoder.encode(orderName, "UTF-8") );
      out.write("\" style=\"");
      out.print( orderSelected ? "color:#3b82f6;font-weight:600;" : "" );
      out.write('"');
      out.write('>');
      out.print( orderName != null ? orderName : "(unnamed)" );
      out.print( orderSelected ? " ▼" : "" );
      out.write("</a></td>\n");
      out.write("                                        <td>");
      out.print( fam );
      out.write("</td>\n");
      out.write("                                    </tr>\n");

                    // Expand families inline under the selected order
                    if (orderSelected) {
                        PreparedStatement psFamily = conn.prepareStatement(
                            "SELECT DISTINCT family_name FROM animalia WHERE order_name=? AND family_name IS NOT NULL AND family_name!='' ORDER BY family_name");
                        psFamily.setString(1, selOrder);
                        ResultSet rsFamily = psFamily.executeQuery();
                        String selFamily = request.getParameter("family");

      out.write("\n");
      out.write("                                    <tr><td colspan=\"2\" style=\"padding:0;\">\n");
      out.write("                                        <div style=\"margin:0.5rem 0 0.5rem 1.5rem;\">\n");
      out.write("                                            <strong style=\"font-size:0.8rem;color:#a1a1aa;\">Families in ");
      out.print( selOrder );
      out.write("</strong>\n");
      out.write("                                            <table style=\"margin-top:0.4rem;width:100%;\">\n");
      out.write("                                                <thead><tr><th>Family</th></tr></thead>\n");
      out.write("                                                <tbody>\n");

                        boolean hasFamilies = false;
                        while (rsFamily.next()) {
                            hasFamilies = true;
                            String familyName = rsFamily.getString("family_name");
                            boolean famSelected = familyName != null && familyName.equals(selFamily);

      out.write("\n");
      out.write("                                                    <tr style=\"");
      out.print( famSelected ? "background:rgba(59,130,246,0.06);" : "" );
      out.write("\">\n");
      out.write("                                                        <td><a href=\"species.jsp?kingdom=");
      out.print( kingdom );
      out.write("&class=");
      out.print( java.net.URLEncoder.encode(selClass, "UTF-8") );
      out.write("&order=");
      out.print( java.net.URLEncoder.encode(selOrder, "UTF-8") );
      out.print( famSelected ? "" : "&family=" + java.net.URLEncoder.encode(familyName, "UTF-8") );
      out.write("\" style=\"");
      out.print( famSelected ? "color:#3b82f6;font-weight:600;" : "" );
      out.write('"');
      out.write('>');
      out.print( familyName != null ? familyName : "(unnamed)" );
      out.print( famSelected ? " ▼" : "" );
      out.write("</a></td>\n");
      out.write("                                                    </tr>\n");

                            // Expand species under selected family
                            if (famSelected) {
                                PreparedStatement psSpecies = conn.prepareStatement(
                                    "SELECT species_name, common_name, description FROM species WHERE family_name=? ORDER BY species_name");
                                psSpecies.setString(1, selFamily);
                                ResultSet rsSpecies = psSpecies.executeQuery();

      out.write("\n");
      out.write("                                                    <tr><td style=\"padding:0;\">\n");
      out.write("                                                        <div style=\"margin:0.5rem 0 0.5rem 1.5rem;\">\n");
      out.write("                                                            <strong style=\"font-size:0.8rem;color:#a1a1aa;\">Species in ");
      out.print( selFamily );
      out.write("</strong>\n");
      out.write("                                                            <table style=\"margin-top:0.4rem;width:100%;\">\n");
      out.write("                                                                <thead><tr><th>Species</th><th>Common Name</th><th>Description</th></tr></thead>\n");
      out.write("                                                                <tbody>\n");

                                boolean hasSpecies = false;
                                while (rsSpecies.next()) {
                                    hasSpecies = true;
                                    String sName = rsSpecies.getString("species_name");
                                    String cName = rsSpecies.getString("common_name");
                                    String desc = rsSpecies.getString("description");

      out.write("\n");
      out.write("                                                                    <tr><td><em>");
      out.print( sName != null ? sName : "" );
      out.write("</em></td><td>");
      out.print( cName != null ? cName : "" );
      out.write("</td><td>");
      out.print( desc != null ? desc : "" );
      out.write("</td></tr>\n");

                                }
                                if (!hasSpecies) {

      out.write("\n");
      out.write("                                                                    <tr><td colspan=\"3\">No species records yet.</td></tr>\n");

                                }
                                rsSpecies.close(); psSpecies.close();

      out.write("\n");
      out.write("                                                                </tbody>\n");
      out.write("                                                            </table>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </td></tr>\n");

                            }
                        }
                        if (!hasFamilies) {

      out.write("\n");
      out.write("                                                    <tr><td>No families found.</td></tr>\n");

                        }
                        rsFamily.close(); psFamily.close();

      out.write("\n");
      out.write("                                                </tbody>\n");
      out.write("                                            </table>\n");
      out.write("                                        </div>\n");
      out.write("                                    </td></tr>\n");

                    }
                }
                if (!hasOrders) {

      out.write("\n");
      out.write("                                    <tr><td colspan=\"2\">No orders found.</td></tr>\n");

                }
                rsOrder.close(); psOrder.close();

      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </td></tr>\n");

            }
        }
        if (!hasRows) {

      out.write("\n");
      out.write("                    <tr><td colspan=\"3\">No classes found for ");
      out.print( kingdom );
      out.write(".</td></tr>\n");

        }
        rsClass.close();
        psClass.close();

      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");

    } catch (Exception e) {

      out.write("\n");
      out.write("        <p style=\"color:#ef4444;\">Database error: ");
      out.print( e.getMessage() != null ? e.getMessage().replace("<","&lt;") : "unknown" );
      out.write("</p>\n");
      out.write("        <p style=\"color:#a1a1aa;font-size:0.8rem;\">User: ");
      out.print( dbProps.getProperty("db.user","?") );
      out.write(" | URL: ");
      out.print( dbProps.getProperty("db.url","?") );
      out.write(" | Props loaded: ");
      out.print( propsLoaded );
      out.write("</p>\n");

    } finally {
        if (conn != null) try { conn.close(); } catch (Exception ignored) {}
    }

      out.write("\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\"><div class=\"footer-bottom\" style=\"border:none;padding:0;\">\n");
      out.write("    <span>&#169; 2026 MEARVK LLC. All rights reserved.</span>\n");
      out.write("</div></footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function() {\n");
      out.write("    var btn = document.getElementById(\"cd1-btn\");\n");
      out.write("    var dialog = document.getElementById(\"cd1-dialog\");\n");
      out.write("    var overlay = document.getElementById(\"cd1-overlay\");\n");
      out.write("    var textarea = document.getElementById(\"cd1-textarea\");\n");
      out.write("    if (!btn || !dialog || !overlay || !textarea) return;\n");
      out.write("    btn.addEventListener(\"click\", function() {\n");
      out.write("        if (dialog.style.display !== \"none\") {\n");
      out.write("            dialog.style.display = \"none\";\n");
      out.write("            overlay.style.display = \"none\";\n");
      out.write("            btn.style.transform = \"\";\n");
      out.write("            btn.style.filter = \"\";\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        btn.style.transform = \"scale(0.9)\";\n");
      out.write("        btn.style.filter = \"drop-shadow(0 0 8px #3b82f6)\";\n");
      out.write("        setTimeout(function() {\n");
      out.write("            btn.style.transform = \"\";\n");
      out.write("            btn.style.filter = \"\";\n");
      out.write("            dialog.style.display = \"block\";\n");
      out.write("            overlay.style.display = \"block\";\n");
      out.write("        }, 750);\n");
      out.write("    });\n");
      out.write("    overlay.addEventListener(\"click\", function() { dialog.style.display = \"none\"; overlay.style.display = \"none\"; });\n");
      out.write("})();\n");
      out.write("function cd1Send() { var s = document.getElementById(\"cd1-action\"); var t = document.getElementById(\"cd1-textarea\"); if(!s||!t)return; t.value += \"[\" + new Date().toLocaleTimeString() + \"] \" + s.value + \" sent.\\n\"; }\n");
      out.write("function cd1Ok() { var t = document.getElementById(\"cd1-textarea\"); if(!t)return; t.value += \"[\" + new Date().toLocaleTimeString() + \"] OK.\\n\"; }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
