#pragma once

#include <cstdint>
#include <string_view>
#include <vector>

namespace utf4088 {

enum class Stage : std::uint8_t { Start, Intermediate, Final };
enum class Language : std::uint8_t { AmericanEnglish, Korean, Germanic };

struct CharacterRecord {
    std::uint32_t integer_id;
    Stage stage;
    Language language;
    std::uint64_t codepoint;
    std::uint64_t shape_id;
    std::uint64_t meaning_id;
};

// Published front-end registry. A release is complete only when it contains
// exactly 16,606 records generated by UTF4088-RG-1.
const std::vector<CharacterRecord>& frontend_registry();

// Deterministically materialize the 16,606-record experimental registry.
std::vector<CharacterRecord> generate_frontend_registry();

// Deterministically derive a renderable remainder symbol from a 4-D address.
std::uint64_t derive_remainder_symbol(double x, double y,
                                      double pressure, double voltage);

std::string_view stage_name(Stage stage);
std::string_view language_name(Language language);

} // namespace utf4088
