package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, July 28, 2026 4:08:09 PM UTC
*/

public interface CodeSets
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CONV_FRAME.CodeSetContext</code> defined in 
       * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
       */
  public static final int value = (int)(1L);
}
