package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, July 28, 2026 4:08:09 PM UTC
*/

public interface TransactionService
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CosTSInteroperation.PropogationContext</code> defined in 
       * <i>CORBAservices: Common Object Services Specifications.</i>
       */
  public static final int value = (int)(0L);
}
